In [ ]:
#!pip install xformers peft accelerate bitsandbytes datasets flash-attn lightning wandb
# for colab
#!pip install xformers peft accelerate bitsandbytes datasets lightning wandb
#!pip install "trl<0.12.0" # when use train_rl_model
#!pip install trl # when use train_reward_model

#!pip uninstall -y trl transformers
#!pip install -q "transformers==4.41.2" "trl==0.9.4" accelerate datasets peft bitsandbytes wandb

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
!zip -r reward_model.zip /content/reward_model

  adding: content/reward_model/ (stored 0%)
  adding: content/reward_model/tokenizer_config.json (deflated 75%)
  adding: content/reward_model/training_args.bin (deflated 53%)
  adding: content/reward_model/vocab.json (deflated 74%)
  adding: content/reward_model/config.json (deflated 51%)
  adding: content/reward_model/special_tokens_map.json (deflated 77%)
  adding: content/reward_model/model.safetensors (deflated 14%)
  adding: content/reward_model/merges.txt (deflated 76%)
  adding: content/reward_model/tokenizer.json (deflated 80%)

In [ ]:
!mkdir -p /content/drive/MyDrive/ru_text_simplification

In [14]:
!cp /content/reward_model.zip /content/drive/MyDrive/ru_text_simplification/

In [1]:
!pip install -q \
  "transformers==4.41.2" \
  "trl==0.9.4" \
  "peft==0.10.0" \
  "accelerate==0.31.0" \
  "datasets==2.20.0" \
  bitsandbytes wandb

In [2]:
!pip install pymorphy3 pymorphy3-dicts-ru

Requirement already satisfied: pymorphy3 in /usr/local/lib/python3.12/dist-packages (2.0.6)
Requirement already satisfied: pymorphy3-dicts-ru in /usr/local/lib/python3.12/dist-packages (2.4.417150.4580142)
Requirement already satisfied: dawg2-python>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from pymorphy3) (0.9.0)
Requirement already satisfied: setuptools>=68.2.2 in /usr/local/lib/python3.12/dist-packages (from pymorphy3) (75.2.0)

In [ ]:
import transformers, trl, peft, accelerate, datasets
print("transformers", transformers.__version__)
print("trl", trl.__version__)
print("peft", peft.__version__)
print("accelerate", accelerate.__version__)
print("datasets", datasets.__version__)

transformers 4.41.2
trl 0.9.4
peft 0.10.0
accelerate 0.31.0
datasets 2.20.0

# data_utils

In [ ]:
import pandas as pd
#import json
#import requests
from typing import Dict, List, Optional, Tuple, Union
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

# new
# helper for cefr conversion
def bucket(lbl: str) -> str:
    if lbl in ("A1", "A2"):
        return "A"
    if lbl in ("B1", "B2"):
        return "B"
    if lbl in ("C1", "C2"):
        return "C"
    raise ValueError(f"Unknown CEFR label: {lbl}")

# new
# helper for cefr conversion
def split_ABC(ts, ls):
    A, B, C = [], [], []
    for t, l in zip(ts, ls):
        b = bucket(l)
        if b == "A":
            A.append(t)
        elif b == "B":
            B.append(t)
        else:
            C.append(t)
    return A, B, C

# unchanged
def get_preference_pairs(priority_list: List[str],
                        other_list_1: List[str],
                        other_list_2: List[str]) -> Tuple[List[str], List[str]]:
    """Create preference pairs for reward modeling."""
    chosen = []
    rejected = []

    # Add samples from priority list as chosen samples
    for sample in priority_list:
        chosen.append(sample)

    # Add samples from other lists as rejected samples
    for sample in other_list_1:
        rejected.append(sample)
    for sample in other_list_2:
        rejected.append(sample)

    # Ensure equal number of chosen/rejected pairs
    rejected = shuffle(rejected, random_state=0)
    if len(chosen) < len(rejected):
        rejected = rejected[:len(chosen)]
    else:
        rejected = [rejected[i % len(rejected)] for i in range(len(chosen))]

    return chosen, rejected


# changed
def load_cefr_data(level: str, mode: str = "reward") -> Union[Dict[str, Dict[str, List[str]]], List[str]]:
    """Load and prepare CEFR data for training.

    Args:
        level: Target CEFR level (A, B, or C)
        mode: Either "reward" for reward modeling or "rl" for RL training

    Returns:
        For reward mode: Dict with train/eval data containing chosen/rejected pairs
        For RL mode: List of training sentences
    """
    # changed
    # load CEFR sentences
    df = pd.read_csv("CEFR_level_sentences.csv", sep=";", encoding="cp1251")
    df = df[["fragment", "textbook-assigned cefr level"]].dropna()
    df["fragment"] = df["fragment"].astype(str).str.strip()
    df["textbook-assigned cefr level"] = df["textbook-assigned cefr level"].astype(str).str.strip().str.upper()
    df = df[df["fragment"] != ""]

    texts = df["fragment"].tolist()
    labels = df["textbook-assigned cefr level"].tolist()

    # changed
    # train dev test split 80/10/10
    try:
        train_texts, temp_texts, train_labels, temp_labels = train_test_split(
            texts, labels, test_size=0.2, random_state=0, stratify=labels
        )
        dev_texts, eval_texts, dev_labels, eval_labels = train_test_split(
            temp_texts, temp_labels, test_size=0.5, random_state=0, stratify=temp_labels
        )
    except Exception:
        train_texts, temp_texts, train_labels, temp_labels = train_test_split(
            texts, labels, test_size=0.2, random_state=0
        )
        dev_texts, eval_texts, dev_labels, eval_labels = train_test_split(
            temp_texts, temp_labels, test_size=0.5, random_state=0
        )

    # changed
    train_A, train_B, train_C = split_ABC(train_texts, train_labels)
    dev_A, dev_B, dev_C = split_ABC(dev_texts, dev_labels)
    test_A, test_B, test_C = split_ABC(eval_texts, eval_labels)


    if mode == "reward":
        # Prepare preference pairs based on target level
        if level == "A":
            train_chosen, train_rejected = get_preference_pairs(train_A, train_B, train_C)
            dev_chosen, dev_rejected = get_preference_pairs(dev_A, dev_B, dev_C)
            eval_chosen, eval_rejected = get_preference_pairs(test_A, test_B, test_C)
        elif level == "B":
            train_chosen, train_rejected = get_preference_pairs(train_B, train_C, train_A)
            dev_chosen, dev_rejected = get_preference_pairs(dev_B, dev_C, dev_A)
            eval_chosen, eval_rejected = get_preference_pairs(test_B, test_C, test_A)
        else:  # level C
            train_chosen, train_rejected = get_preference_pairs(train_C, train_B, train_A)
            dev_chosen, dev_rejected = get_preference_pairs(dev_C, dev_B, dev_A)
            eval_chosen, eval_rejected = get_preference_pairs(test_C, test_B, test_A)

        return {
            "train": {"chosen": train_chosen, "rejected": train_rejected},
            "dev": {"chosen": dev_chosen, "rejected": dev_rejected},
            "eval": {"chosen": eval_chosen, "rejected": eval_rejected}
        }

    elif mode == "rl":  # mode == "rl"
        # For RL training, return sentences of target level
        if level == "A":
            return train_A
        elif level == "B":
            return train_B
        else:
            return train_C
    else:
        raise ValueError(f"Invalid mode: {mode}")


# changed all
def read_complicated_lines(path: str,
                          *,
                          min_len: int = 1,
                          max_cos_sim: Optional[float] = None) -> List[str]:
    """
    Reads csv with source and target sentences

    Returns:
        List[str] of complex source sentences (RL inputs)

    Args:
        path: path to source_target_sentences.csv
        min_len: drop sources shorter than this many characters
        max_cos_sim: keep only rows with cos_sim <= max_cos_sim
                     (to avoid identical source/target)
    """
    df = pd.read_csv(path, sep=";", encoding="cp1251")

    if "source" not in df.columns:
        raise ValueError(f"Expected column 'source' in {path}, got columns: {list(df.columns)}")

    src = df["source"].dropna().astype(str).str.strip()
    src = src[src != ""]

    # optional quality filters
    if min_len > 1:
        src = src[src.str.len() >= min_len]

    if max_cos_sim is not None:
        if "cos_sim" not in df.columns:
            raise ValueError("max_cos_sim was set but column 'cos_sim' is missing in the CSV.")
        cos = pd.to_numeric(df.loc[src.index, "cos_sim"], errors="coerce")
        src = src[cos <= max_cos_sim]

    return src.tolist()

# changed all
def get_complicated_sentence(path: str,
                             *,
                             min_len: int = 1,
                             max_cos_sim: Optional[float] = None) -> List[str]:
    """
    Returns the same thing as read_complicated_lines().
    """
    return read_complicated_lines(path, min_len=min_len, max_cos_sim=max_cos_sim)

# Modeling

### Lexical reward model

In [4]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string
from typing import List, Dict, Union
import pandas as pd
import re
from tqdm import tqdm
from typing import Tuple

# new
import nltk
nltk.download("stopwords")
nltk.download('punkt')
from dataclasses import dataclass
from typing import List, Tuple, Union, Dict, Optional
import pymorphy3

# new
CEFR2ABC = {"A1":"A","A2":"A","B1":"B","B2":"B","C1":"C","C2":"C"}

# new
RU_STOP = set(stopwords.words("russian"))


class LexicalRewardModelRU:
    # changed lemmatizer to Russian
    def __init__(self, level: str, word_list_path: str):
        """Initialize lexical reward model for CEFR level."""
        self.level = level
        self.lemmatizer = pymorphy3.MorphAnalyzer()
        self.word_list, self.negative_word_list = self._load_word_lists(word_list_path)
        self.word_reward_dict = {idx: 1.0 for idx in range(len(self.word_list))}
        self.word_freq_dict = {idx: 0 for idx in range(len(self.word_list))}


    # new
    def _lemmatize(self, token: str) -> str:
        return self.lemmatizer.parse(token.lower())[0].normal_form


    # almost not changed, just type check
    def _load_word_lists(self, path: str) -> Tuple[List[Union[str, List[str]]], List[Union[str, List[str]]]]:
        """Load and process CEFR word lists."""
        df = pd.read_csv(path)

        # new
        # safety checks
        df["level"] = df["level"].astype(str).str.strip().str.upper()
        df["base"] = df["base"].astype(str).str.strip()

        # Filter words based on level
        if self.level == "A":
            level_df = df[df['level'].isin(['A1', 'A2'])]
            negative_df = df[df['level'].isin(['B1', 'B2', 'C1', 'C2'])]
        elif self.level == "B":
            level_df = df[df['level'].isin(['B1', 'B2'])]
            negative_df = df[df['level'].isin(['C1', 'C2'])]
        else:  # level C
            level_df = df[df['level'].isin(['C1', 'C2'])]
            negative_df = pd.DataFrame(columns=df.columns)

        word_list = list(set([tuple(self._process_word(w)) for w in level_df['base'].tolist()]))
        negative_word_list = list(set([tuple(self._process_word(w)) for w in negative_df['base'].tolist()]))

        return word_list, negative_word_list


    # unchanged
    def _process_word(self, word: str) -> Union[str, List[str]]:
        """Process a word or phrase from the CEFR profile word list based on a set of rules."""
        # TODO: update to add more rules
        word = word.strip()
        if len(word.split()) > 1:  # phrase
            # 1. remove ", etc.", "be"
            phrase = word.replace(", etc.", "").replace("be", "").replace(" to do sth", "")
            # 2. remove anything in ()
            phrase = re.sub(r'\(.*?\)', '', phrase)
            # 3. split with " or "
            phrases = phrase.split(" or ")[:1]
            processed = []
            for p in phrases:
                # 4. deal with sb/sth
                p = p.replace("sb/sth", "...").replace("sb", "...").replace("sth", "...")
                # 5. deal with / and ()
                if "/" in p:
                    parts = p.split()
                    new_parts = []
                    for part in parts:
                        if "/" in part:
                            part = part.split("/")[0]
                        new_parts.append(part)
                    p = " ".join(new_parts)

                # 6. deal with ...
                if "..." in p:
                    p = [x.lstrip().rstrip() for x in p.split("...") if x.strip()]
                else:
                    p = [p.lstrip().rstrip()]

                processed.extend([re.sub(r'\s+', ' ', x).lower() for x in p if x])# replace multiple blank

            return list(set(processed))

        return word.lower()


    # unchanged
    def compute_reward(self, text: str) -> float:
        """Compute lexical reward for a text."""
        tokens_no_stop, tokens_with_stop = self._preprocess_text(text)

        score = 0
        negative_score = 0
        matched = []
        negative_matched = []

        #TODO: update the matching algorithm
        # Match single words
        for token in tokens_no_stop:
            for w in self.word_list:
                # is word and exactly the same
                if isinstance(w, str) and token == w:
                    matched.append(token)
                    score += self.word_reward_dict[self.word_list.index(w)]
                    break

            for w in self.negative_word_list:
                if isinstance(w, str) and token == w:
                    negative_matched.append(token)
                    negative_score -= 1
                    break

        # Match phrases
        text_to_match = " ".join(tokens_with_stop)
        for idx, w in enumerate(self.word_list):
            if isinstance(w, list):
                if len(w) == 1:  # continuous phrase
                    if w[0] in text_to_match:
                        matched.append(w[0])
                        multiplier = 1.3 if len(w[0].split()) > 1 else 1.0
                        score += multiplier * self.word_reward_dict[idx]
                else:  # discontinuous phrase
                    matched_parts = 0
                    remaining_text = text_to_match
                    for part in w:
                        if len(part.split()) > 1 and part in remaining_text:
                            matched_parts += 1
                            remaining_text = "".join(remaining_text.split(part)[1:])

                    if matched_parts > 0:
                        score += 1.3 * (matched_parts / len(w)) * self.word_reward_dict[idx]

        final_score = score + negative_score
        return final_score / len(tokens_no_stop) if tokens_no_stop else 1.0


    # changed lemmatizer.lemmatize --> _lemmatize and stopwords
    def _preprocess_text(self, text: str) -> Tuple[List[str], List[str]]:
        """Preprocess text for matching."""
        stop_words = RU_STOP
        tokens = word_tokenize(text.lower())
        tokens = [w for w in tokens if w not in string.punctuation]

        tokens_no_stop = [w for w in tokens if w not in stop_words]
        tokens_no_stop = [self._lemmatize(w) for w in tokens_no_stop]

        tokens_with_stop = [self._lemmatize(w) for w in tokens]

        return tokens_no_stop, tokens_with_stop


    # unchanged
    def update_rewards(self, generations: List[str]):
        """Update reward weights based on word frequencies in generations."""
        # after each epoch, adjust the score for each matched token #
        # based on the tokens frequency, and IDF #
        # frequency is calculated globally, is the overall count for the token #
        # IDF is to encourage more generations to have rare words,
        # common words across all generations will have less score
        # ### but we no not want word appear only in one generation

        self.word_freq_dict = {idx: 0 for idx in range(len(self.word_list))}

        for text in tqdm(generations):
            tokens_no_stop, tokens_with_stop = self._preprocess_text(text)
            text_to_match = " ".join(tokens_with_stop)

            # Count word frequencies
            for idx, w in enumerate(self.word_list):
                if isinstance(w, str):
                    if w in tokens_no_stop:
                        self.word_freq_dict[idx] += 1
                else:  # phrase
                    if len(w) == 1:
                        if w[0] in text_to_match:
                            self.word_freq_dict[idx] += 1
                    else:
                        matched = False
                        for part in w:
                            if len(part.split()) > 1 and part in text_to_match:
                                matched = True
                        if matched:
                            self.word_freq_dict[idx] += 1

        # Update rewards based on frequencies
        total_words = sum(self.word_freq_dict.values())
        for idx in self.word_freq_dict:
            tf = self.word_freq_dict[idx] / total_words if total_words > 0 else 0
            if tf >= 1/len(self.word_list):
                self.word_reward_dict[idx] = 2**(-10*tf)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

### Config

In [5]:
from dataclasses import dataclass
from typing import Optional, List, Literal


@dataclass
class PairwiseRewardModelConfig:
    model_name: str = "ai-forever/rugpt3small_based_on_gpt2"
    num_labels: int = 1
    level: str = "A" # "A", "B", or "C"
    train_batch_size: int = 32
    eval_batch_size: int = 32
    learning_rate: float = 1.41e-5
    # changed to 5
    num_train_epochs: int = 5
    gradient_accumulation_steps: int = 2
    output_dir: str = "./reward_model/"
    max_length: int = 128
    wandb_project: str = "CEFR-RewardModel"
    wandb_exp_name: Optional[str] = None


@dataclass
class RLTrainingConfig:
    training_sentences_path: Optional[str] = None
    model_name: str = "microsoft/Phi-3-mini-4k-instruct"
    level: str = "A" # "A", "B", or "C"
    batch_size: int = 48
    mini_batch_size: int = 16
    generate_bs: int = 32
    learning_rate: float = 3e-5
    ppo_epochs: int = 10
    max_new_tokens: int = 64
    gradient_accumulation_steps: int = 3
    output_dir: str = "./rl_model/"
    wandb_project: str = "PPO-training-sentence-simplification"
    wandb_exp_name: Optional[str] = None
    word_list_path: str = "./new_vocabulary.csv"
    lora_r: int = 16
    lora_alpha: int = 32
    lora_dropout: float = 0.2

@dataclass
class BeamSearchConfig:
    base_model_path: str
    condition_model_path: str
    condition_tokenizer_path: str
    level: int  # CEFR level 1-6
    condition_type: Literal["bert", "gpt2"]
    condition_lambda: float = 0.8
    topk: int = 200
    num_beams: int = 5
    max_new_tokens: int = 100
    do_sample: bool = False

### Pairwise reward model

In [6]:
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from typing import List, Dict, Optional
from tqdm import tqdm
from datasets import Dataset
from trl import RewardTrainer, RewardConfig
#from config import PairwiseRewardModelConfig
import os
#from data_utils import load_cefr_data

class CEFRRewardModel:
    def __init__(self, config: PairwiseRewardModelConfig):
        self.config = config
        self.model = self._init_model()
        self.tokenizer = self._init_tokenizer()


    def _init_model(self):
        model = AutoModelForSequenceClassification.from_pretrained(
            self.config.model_name,
            num_labels=self.config.num_labels,
            #torch_dtype=torch.bfloat16,
            #attn_implementation="flash_attention_2"
            #torch_dtype=torch.float16,
            attn_implementation="eager"
        )
        model.config.pad_token_id = model.config.eos_token_id
        return model.to('cuda')

    def _init_tokenizer(self):
        tokenizer = AutoTokenizer.from_pretrained(self.config.model_name)
        tokenizer.pad_token = tokenizer.eos_token
        return tokenizer

    def prepare_dataset(self, chosen_texts: List[str], rejected_texts: List[str]) -> Dataset:
        dataset = Dataset.from_dict({
            "chosen": chosen_texts,
            "rejected": rejected_texts
        })

        def preprocess(examples):
            new_examples = {
                "input_ids_chosen": [],
                "attention_mask_chosen": [],
                "input_ids_rejected": [],
                "attention_mask_rejected": [],
            }
            for chosen, rejected in zip(examples["chosen"], examples["rejected"]):
                tokenized_chosen = self.tokenizer(chosen)
                #tokenized_chosen = self.tokenizer(chosen, truncation=True, max_length=self.config.max_length)
                tokenized_rejected = self.tokenizer(rejected)
                #tokenized_rejected = self.tokenizer(rejected, truncation=True, max_length=self.config.max_length)

                new_examples["input_ids_chosen"].append(tokenized_chosen["input_ids"])
                new_examples["attention_mask_chosen"].append(tokenized_chosen["attention_mask"])
                new_examples["input_ids_rejected"].append(tokenized_rejected["input_ids"])
                new_examples["attention_mask_rejected"].append(tokenized_rejected["attention_mask"])

            return new_examples
        dataset = dataset.map(preprocess, batched=True, num_proc=torch.cuda.device_count())
        dataset = dataset.filter(lambda x: len(x["input_ids_chosen"]) <= self.config.max_length and len(x["input_ids_rejected"]) <= self.config.max_length)
        return dataset

    def train(self):
        print("Loading CEFR data... ")
        data = load_cefr_data(self.config.level, mode="reward")

        train_dataset = self.prepare_dataset(data["train"]["chosen"], data["train"]["rejected"])
        dev_dataset = self.prepare_dataset(data["dev"]["chosen"], data["dev"]["rejected"])
        eval_dataset = self.prepare_dataset(data["eval"]["chosen"], data["eval"]["rejected"])

        os.environ["WANDB_PROJECT"]=self.config.wandb_project
        os.environ['WANDB_WATCH'] = 'false'  # used in Trainer
        os.environ['WANDB_NAME'] = 'reward-model'  # used in Trainer
        training_args = RewardConfig(
            per_device_train_batch_size=self.config.train_batch_size,
            per_device_eval_batch_size=self.config.eval_batch_size,
            learning_rate=self.config.learning_rate,
            num_train_epochs=self.config.num_train_epochs,
            gradient_accumulation_steps=self.config.gradient_accumulation_steps,
            output_dir=self.config.output_dir,
            #bf16=True,
            #fp16=True, # new
            report_to = "wandb",
            logging_steps=1,
            eval_steps=10,
            max_length=self.config.max_length, # new
            remove_unused_columns=False, # new
        )

        trainer = RewardTrainer(
            model=self.model,
            #processing_class=self.tokenizer,
            tokenizer=self.tokenizer,
            train_dataset=train_dataset,
            eval_dataset=dev_dataset,
            args=training_args
        )

        trainer.train()
        trainer.evaluate(eval_dataset=eval_dataset)
        trainer.save_model(self.config.output_dir)

    def compute_rewards(self, texts: List[str]) -> torch.Tensor:
        """Compute rewards for generated texts."""
        rewards = []

        with torch.no_grad():
            for i in range(0, len(texts), self.config.eval_batch_size):
                batch = texts[i:i + self.config.eval_batch_size]
                inputs = self.tokenizer(batch, return_tensors="pt", padding=True)
                inputs = {k: v.to("cuda") for k, v in inputs.items()}

                logits = torch.sigmoid(self.model(**inputs).logits)
                rewards.append(logits)
        res = torch.vstack(rewards).cpu()
        res = res.to(torch.float32)

        return res

    @classmethod
    def load_model(cls, path: str):
        """Load a saved reward model."""
        model = AutoModelForSequenceClassification.from_pretrained(
            path,
            num_labels=1,
            #torch_dtype=torch.bfloat16,
            # attn_implementation="flash_attention_2"
            torch_dtype=torch.float16,
            attn_implementation="eager"
        )
        tokenizer = AutoTokenizer.from_pretrained(path)
        tokenizer.pad_token = tokenizer.eos_token

        model.config.pad_token_id = model.config.eos_token_id
        model.to('cuda')
        model.eval()

        return model, tokenizer

## Reward Evaluation

In [7]:
import numpy as np

def get_pairwise_scores(reward_model, level: str, limit: int = None):
    data = load_cefr_data(level, mode="reward")
    chosen = data["eval"]["chosen"]
    rejected = data["eval"]["rejected"]

    if limit is not None:
        chosen = chosen[:limit]
        rejected = rejected[:limit]

    chosen_scores = reward_model.compute_rewards(chosen).squeeze(-1).cpu().numpy()
    rejected_scores = reward_model.compute_rewards(rejected).squeeze(-1).cpu().numpy()
    return chosen_scores, rejected_scores


def pairwise_accuracy(chosen_scores, rejected_scores):
    diffs = chosen_scores - rejected_scores
    wins = np.sum(diffs > 0)
    ties = np.sum(diffs == 0)
    total = len(diffs)
    return {
        "pairwise_accuracy": float(wins / total),
        #"ties": int(ties),
        "n_pairs": int(total),
    }


def pairwise_margin(chosen_scores, rejected_scores):
    diffs = chosen_scores - rejected_scores
    return {
        "mean_margin": float(np.mean(diffs)),
        #"std_margin": float(np.std(diffs)),
    }


def bucket_mean_scores(reward_model, limit: int = None):
    A_texts = load_cefr_data("A", mode="rl")
    B_texts = load_cefr_data("B", mode="rl")
    C_texts = load_cefr_data("C", mode="rl")

    if limit is not None:
        A_texts = A_texts[:limit]
        B_texts = B_texts[:limit]
        C_texts = C_texts[:limit]

    return {
        "A_mean": float(reward_model.compute_rewards(A_texts).mean().item()),
        "B_mean": float(reward_model.compute_rewards(B_texts).mean().item()),
        "C_mean": float(reward_model.compute_rewards(C_texts).mean().item()),
    }


def evaluate_reward_model(reward_model, level: str, limit: int = None):
    chosen_scores, rejected_scores = get_pairwise_scores(reward_model, level, limit=limit)

    results = {"level": level}
    results.update(pairwise_accuracy(chosen_scores, rejected_scores))
    results.update(pairwise_margin(chosen_scores, rejected_scores))
    results.update(bucket_mean_scores(reward_model, limit=limit))

    return results

# Train

### Train_reward_model

## 2 epochs - A

In [ ]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="A")
    parser.add_argument("--model_name", type=str, default="ai-forever/rugpt3small_based_on_gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=2)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()

    print("MODEL:", args.model_name)
    print("LEVEL:", args.level)
    print("EPOCHS:", args.num_train_epochs)

    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

MODEL: ai-forever/rugpt3small_based_on_gpt2
LEVEL: A
EPOCHS: 2

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/720 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/551M [00:00<?, ?B/s]

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ai-forever/rugpt3small_based_on_gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/574 [00:00<?, ?B/s]

Loading CEFR data...

Map:   0%|          | 0/1519 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1519 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Filter:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Filter:   0%|          | 0/189 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Думали ли читатели рассказов Рэя Бредбери,    │ Слово «экология» знают сейчас все люди. Как  │ [0.9082, 0.0918] │
│ что в нашей жизни будут «социальные сети» и   │ правило, его используют для характеристики   │                  │
│ мобильные телефоны, о которых он писал?       │ условий проживания: «хорошая (плохая)        │                  │
│                                               │ экология», «в нашем районе – ужасная         │                  │
│                                               │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В 17:45 я иду в супермаркет и покупаю         │ В 1970 году с благословения Американской     │ [0.993, 0.007]   │
│ продукты. Потом я иду домой и готовлю ужин.   │ академии религии Гэскин едет в тур по        │                  │
│ До ужина я ещё убираю квартиру. В 20:00 я     │ Америке — беседовать о духовности с          │                  │
│ ужинаю.                                       │ молодёжью. За ним, на машинах и школьных     │                  │
│                                               │ автобусах, едут его последователи.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я помню, несколько лет назад я была в банке.  │ Потратить деньги на какую-нибудь не очень    │ [0.9975, 0.0025] │
│ Там работал очень красивый мужчина. Мы        │ нужную вещь значит забыть на пару часов о    │                  │
│ познакомились, и он пригласил меня в кино.    │ проблемах в отношениях и на работе.          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вы его, конечно, тоже знаете, но называете    │ Мы отдалились от природы, поэтому не ценим и │ [0.9383, 0.0617] │
│ «русский салат». Ингредиенты в «Оливье» очень │ не уважаем её. Природа отвечает нам тем же.  │                  │
│ простые. Это картофель, морковь, зелёный      │ Примером может служить изменение погоды и    │                  │
│ горошек, яйца, солёные огурцы и мясо. Иногда  │ климата на всей планете.                     │                  │
│ этот салат делают без мяса.                   │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Этому городу уже 500 лет. В Плёсе есть        │ Г В этом сезоне нас чаще всего «лечили»      │ [0.8843, 0.1157] │
│ Дом-музей художника Исаака Ильича Левитана.   │ простуженные граждане, на остановке          │                  │
│ Этот известный художник очень любил природу,  │ ожидающие автобус. Помните, девушка          │                  │
│ поэтому он жил и работал в этом тихом зелёном │ «вылечила» от простуды стареющего рокера: —  │                  │
│ городе.                                       │ Апчхи. О, эта простуда.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На вертолёте он перелетел через Красное море, │ Гости могут принести вам хлеб и соль, это    │ [0.9668, 0.0332] │
│ прилетел в Аравию, а оттуда на машине поехал  │ символический жест по немецкой традиции.     │                  │
│ в Иран.                                       │ Подарки дарят разные.                        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Оно ему очень нравится. Послушайте: в         │ Суть в том, что ритейлеры перепродают        │ [0.9968, 0.0032] │
│ институте Антон показал книгу и автограф      │ небольшим магазинам товары, полученные от    │                  │
│ поэта Джону, Кларе, Марии и Анне. Антон       │ производителей со скидкой. В итоге они       │                  │
│ рассказал им, что поэт будет выступать в      │ сохраняют скидку за объём продаж, но до      │                  │
│ институте на вечере.                          │ реального покупателя эти скидки не доходят.  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Сейчас 7 часов 30 минут. Люди идут на работу. │ В 1935 году на Воробьёвых горах прошёл       │ [0.9978, 0.0022] │
│ Вот Иван Иванович. Он преподаватель. Он идёт  │ первый чемпионат СССР по прыжкам на лыжах с  │                  │
│ в университет. А это его жена. Она работает в │ трамплина и второй чемпионат СССР по         │                  │
│ библиотеке.                                   │ горнолыжному спорту.                         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Например, я покупал новую кофту, если на      │ С того времени несёт она свои воды в Енисей. │ [0.8393, 0.1607] │
│ улице была холодная погода, а утром я надел   │ А камень, который бросил Байкал, и сейчас    │                  │
│ только футболку. Результат — много            │ стоит на том же месте.                       │                  │
│ некачественных вещей, которые я не ношу.      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ — На Волхонке, недалеко от станции метро      │ Бутерброд — одно из самых любимых и простых  │ [0.0815, 0.9185] │
│ «Кропоткинская», — ответил им молодой         │ блюд, мы едим его на завтрак или на обед,    │                  │
│ человек. — А как добраться до музея? —        │ когда нет времени приготовить что-то другое. │                  │
│ Удобнее всего доехать на метро, здесь рядом   │                                              │                  │
│ станция метро «Арбатская».                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Рауль — студент из Испании. Он учится в       │ Полученные деньги она отдала сыну, чтобы он  │ [0.9512, 0.0488] │
│ Московском университете на экономическом      │ мог поехать в столицу и продолжить там своё  │                  │
│ факультете. Он учится не очень хорошо и       │ образование. Так летом 1954 года В. М.       │                  │
│ поэтому плохо сдаёт экзамены.                 │ Шукшин оказался в Москве.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ А как вы считаете, можно самостоятельно       │ В 1926 году её приняли в Музыкальный театр,  │ [0.9305, 0.0695] │
│ изучить язык? Да, конечно. Очень важно        │ в котором несколько лет она пела в хоре и    │                  │
│ заниматься языком каждый день.                │ изучала актёрское мастерство.                │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Утром я везу подарки детям в детские сады или │ Столицей тогда была Москва, Петербург ещё не │ [0.941, 0.059]   │
│ школы. Я играю с детьми, пою с ними песни, а  │ был построен. В Москве встреча Нового года   │                  │
│ они читают мне стихи. Вечером я везу подарки  │ проходила на Красной площади, где были       │                  │
│ взрослым.                                     │ массовые гуляния.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Целый год мать ухаживает за девушкой. Она     │ Иметь «крутой» мобильный телефон — мечта     │ [0.9773, 0.0227] │
│ кормит её, как ребёнка, даёт ей лекарство,    │ каждого подростка, ведь стоимость аппарата,  │                  │
│ проводит с ней всё свободное время. И         │ по их убеждению, красноречиво говорит о      │                  │
│ благодаря матери девушка выздоравливает.      │ «крутизне» его владельца.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я думаю, можно в кафе. Но я не знаю, где ты   │ Эта методика популярна в тёплых странах, где │ [0.9589, 0.0411] │
│ живёшь. На какой улице? Там есть хорошее      │ много собак, которые живут на улице:         │                  │
│ кафе? Маша — Саше: Саша, можно встретиться в  │ Бангладеш, Румыния, Греция, Таиланд,         │                  │
│ кафе в центре города.                         │ Индонезия, Индия.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ История рассказывает о девочке, которая       │ Впервые этот праздник отметили в 1911 году,  │ [0.855, 0.145]   │
│ попадает в нереальный мир под землёй. © Это   │ но только 19 марта, в Австрии, Дании,        │                  │
│ роман о трагической любви замужней женщины по │ Германии и Швейцарии.                        │                  │
│ имени Анна и офицера.                         │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Игорь: «В воскресенье я обычно хожу в         │ Или, например, были у него или не были       │ [0.826, 0.174]   │
│ библиотеку. Только в этот день я могу не      │ карточки, которые в разные периоды           │                  │
│ ходить в университет».                        │ существовали и играли важную роль при        │                  │
│                                               │ покупке продуктов в СССР.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Эта статья не о таких людях, а о тех, кто     │ Всё это прошло перед её глазами, в её глазах │ [0.6792, 0.3208] │
│ решил отказаться от комфорта и отправился в   │ покоилась мудрость веков, и, глядя в них, я  │                  │
│ путешествие, чтобы увидеть весь мир. Слово    │ чувствовал себя совсем маленьким и нагим.    │                  │
│ «путешествовать» значит «идти пешком».        │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ После бани хорошо поплавать в холодном        │ Для лучшего запоминания также используются   │ [0.8492, 0.1508] │
│ бассейне или принять холодный душ. И, как     │ цвета, звуковые комбинации, яркие образы.    │                  │
│ говорят в России, «С лёгким паром!».          │ Правильно применяя метод дворца памяти,      │                  │
│                                               │ можно запомнить информацию на долгие годы.   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Потом мы рассказывали, чем мы занимаемся в    │ После ядерной войны с применением массового  │ [0.9995, 0.0005] │
│ свободное время. Сирпа любит гостей и с       │ секретного оружия от Российской Федерации    │                  │
│ удовольствием готовит. Клаус много гуляет,    │ осталась лишь небольшая часть, которая       │                  │
│ часто ездит в лес. Том занимается спортом.    │ называет себя Московской империей.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Ещё у него есть младший брат. Его зовут       │ Естественно предположить, что пришельцы, как │ [0.999, 0.001]   │
│ Валерий. Ему 38 лет. Он тоже хоккеист. Сейчас │ это всегда и бывает, осваивали в первую      │                  │
│ он уже не играет в хоккей, но он ещё          │ очередь побережье, истребляя попутно леса по │                  │
│ занимается спортом.                           │ всему периметру континента.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Город быстро стал торговым портом и           │ Вот несколько советов, которые помогут вашей │ [0.8028, 0.1972] │
│ культурным центром, одним из самых красивых   │ памяти работать хорошо. Соедините предмет и  │                  │
│ мест мира. Он не был похож на Москву, его     │ действие, которое вы делаете автоматически!  │                  │
│ строили по точному плану.                     │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Конечно, в час пик в общественном транспорте  │ Часто участники должны вести себя            │ [0.9399, 0.0601] │
│ очень много народу, и это не всегда приятно.  │ по-клоунски, и они перестают комплексовать:  │                  │
│ Молодые люди очень громко разговаривают по    │ «Я выгляжу как полный дурак и не боюсь       │                  │
│ мобильному телефону или слушают музыку.       │ посмеяться над собой».                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Как я любил тебя», — писал Пушкин». Клара:   │ У меня не было близкого друга, когда я       │ [0.4523, 0.5477] │
│ «Я очень рада, что была в Доме-музее Пушкина  │ училась в школе и университете, потому что я │                  │
│ на Арбате. Там на портрете я видела поэта и   │ была очень скромная, можно сказать, тихоня.  │                  │
│ его жену».                                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Но хорошие способности помогли ему стать      │ Общая сумма пожертвований превысила 700      │ [0.9962, 0.0038] │
│ студентом академии. Ему было очень трудно     │ тысяч рублей, позволив облегчить жизнь       │                  │
│ учиться: он был намного старше, чем другие    │ жестоко страдающим людям. Информированность  │                  │
│ ученики. Учился Ломоносов сначала в Москве,   │ о БАС во всём мире повысилась настолько, что │                  │
│ потом в Петербурге.                           │ и мечтать было невозможно.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Это очень хорошая ситуация, но есть проблема: │ — Наверное, это наивный вопрос, но, как вы   │ [0.7208, 0.2792] │
│ как инвестировать эти деньги? Когда ваши      │ считаете, деньги делают людей счастливыми? — │                  │
│ деньги дома — это непрактично, потому что     │ На этот вопрос у меня есть точный ответ:     │                  │
│ есть инфляция. Что делать?                    │ нет, не делают.                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Павел Дуров родился в Ленинграде 10 октября   │ Великий Новгород кормился ростовским хлебом  │ [0.9374, 0.0626] │
│ 1984 года. Его папа, профессор классической   │ и «зело страдал», когда дороги были          │                  │
│ филологии, несколько лет работал в Италии, в  │ непроезжи. Тысячу лет Ополье не устаёт       │                  │
│ Турине, и там Павел начал учиться в школе.    │ кормить человека.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ И вы знаете, что случилось в этот вечер?!     │ Сергей Петров — владелец крупной             │ [0.911, 0.089]   │
│ Анна тоже была на концерте. Это был также и   │ компьютерной компании «Информатика». Сергей  │                  │
│ её любимый музыкант. Она не знала, что я      │ родился в Советском Союзе, в те годы, когда  │                  │
│ хотел идти на концерт.                        │ в стране такой профессии, как бизнесмен,     │                  │
│                                               │ вообще не существовало.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Реальный Рэп может читать только тот, кто    │ Они хотят быть похожими на своих кумиров     │ [0.6117, 0.3883] │
│ сам его пишет» — так комментирует Децл свою   │ Илона Маска, Марка Цукерберга, Билла Гейтса  │                  │
│ работу.                                       │ и Стива Джобса, бросивших учёбу в            │                  │
│                                               │ университете, но добившихся больших успехов  │                  │
│                                               │ и ставших известными во всём мире.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Студенты — люди, как правило, небогатые,      │ Это мог быть доклад министра или приём       │ [0.9929, 0.0071] │
│ потому что они не работают. Так думал         │ крупного сановника. В 17 часов следовал      │                  │
│ журналист. У него были такие вопросы: «Как вы │ обязательный чай. Чаепитие обычно            │                  │
│ отдыхаете, куда вы обычно ходите в            │ продолжалось не более получаса.              │                  │
│ воскресенье?»                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вечером вся семья дома. Папа читает газеты,   │ И сегодня во многих исламских странах можно  │ [0.9662, 0.0338] │
│ мама готовит ужин, Игорь делает домашнее      │ увидеть бездомных, голодных, худых собак.    │                  │
│ задание, а Лена играет.                       │ Правда, так не везде, например, в Стамбуле   │                  │
│                                               │ бездомные псы толстые и весёлые.             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ У Алины мало свободного времени, но у неё     │ Однако с советской стороны была проведена    │ [0.9964, 0.0036] │
│ есть много увлечений: она любит животных      │ артподготовка, которая нанесла сильный удар  │                  │
│ (особенно своих собак), прекрасно рисует и    │ по врагу, лишила его преимуществ             │                  │
│ мечтает открыть ресторан японской кухни.      │ неожиданности и не позволила немцам          │                  │
│                                               │ реализовать свой план.                       │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Думали ли читатели рассказов Рэя Бредбери,    │ Слово «экология» знают сейчас все люди. Как  │ [0.9082, 0.0918] │
│ что в нашей жизни будут «социальные сети» и   │ правило, его используют для характеристики   │                  │
│ мобильные телефоны, о которых он писал?       │ условий проживания: «хорошая (плохая)        │                  │
│                                               │ экология», «в нашем районе – ужасная         │                  │
│                                               │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В 17:45 я иду в супермаркет и покупаю         │ В 1970 году с благословения Американской     │ [0.993, 0.007]   │
│ продукты. Потом я иду домой и готовлю ужин.   │ академии религии Гэскин едет в тур по        │                  │
│ До ужина я ещё убираю квартиру. В 20:00 я     │ Америке — беседовать о духовности с          │                  │
│ ужинаю.                                       │ молодёжью. За ним, на машинах и школьных     │                  │
│                                               │ автобусах, едут его последователи.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я помню, несколько лет назад я была в банке.  │ Потратить деньги на какую-нибудь не очень    │ [0.9975, 0.0025] │
│ Там работал очень красивый мужчина. Мы        │ нужную вещь значит забыть на пару часов о    │                  │
│ познакомились, и он пригласил меня в кино.    │ проблемах в отношениях и на работе.          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вы его, конечно, тоже знаете, но называете    │ Мы отдалились от природы, поэтому не ценим и │ [0.9383, 0.0617] │
│ «русский салат». Ингредиенты в «Оливье» очень │ не уважаем её. Природа отвечает нам тем же.  │                  │
│ простые. Это картофель, морковь, зелёный      │ Примером может служить изменение погоды и    │                  │
│ горошек, яйца, солёные огурцы и мясо. Иногда  │ климата на всей планете.                     │                  │
│ этот салат делают без мяса.                   │                                              │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.9983305335044861 Я люблю читать книги.
0.9804269075393677 Сегодня хорошая погода.
0.9906908273696899 Мне нравится гулять в парке.
0.09505032747983932 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.004655271302908659 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.03013445995748043 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [ ]:
results = evaluate_reward_model(pairwise_reward_model, level="A")
print(results)

{'level': 'A', 'pairwise_accuracy': 0.8835978835978836, 'n_pairs': 189, 'mean_margin': 0.4401126801967621, 'A_mean': 0.8947047591209412, 'B_mean': 0.48260441422462463, 'C_mean': 0.283855140209198}

In [ ]:
results["model"] = "rugpt"
results["epochs"] = 2
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_rugpt_2_A.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,A,0.883598,189,0.440113,0.894705,0.482604,0.283855,gpt2,2

## 2 epochs - B

In [8]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="B")
    parser.add_argument("--model_name", type=str, default="ai-forever/rugpt3small_based_on_gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=2)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()

    print("MODEL:", args.model_name)
    print("LEVEL:", args.level)
    print("EPOCHS:", args.num_train_epochs)

    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

MODEL: ai-forever/rugpt3small_based_on_gpt2
LEVEL: B
EPOCHS: 2

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/720 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/551M [00:00<?, ?B/s]

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ai-forever/rugpt3small_based_on_gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/574 [00:00<?, ?B/s]

Loading CEFR data...

Map:   0%|          | 0/3273 [00:00<?, ? examples/s]

Filter:   0%|          | 0/3273 [00:00<?, ? examples/s]

Map:   0%|          | 0/408 [00:00<?, ? examples/s]

Filter:   0%|          | 0/408 [00:00<?, ? examples/s]

Map:   0%|          | 0/410 [00:00<?, ? examples/s]

Filter:   0%|          | 0/410 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Это значит, мы приезжаем к университету, вы   │ У меня есть подруга, я её очень люблю, и всё │ [0.4637, 0.5363] │
│ выходите из машины и идёте учиться. Отвозить  │ мне в ней нравится. У неё длинные густые     │                  │
│ или отвезти кого-то куда-то – это значит      │ волнистые каштановые волосы, высокий умный   │                  │
│ привезти человека в какое-то место и оставить │ лоб и вздёрнутый кверху задорный носик.      │                  │
│ там. Понятно?                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Форт № 11 «Дёнхофф» был построен в XIX веке и │ Сегодня это не просто миллионы селфи         │ [0.6943, 0.3057] │
│ хорошо сохранился. Здесь проходят экскурсии и │ туристов и моделей. Компании часто           │                  │
│ даже квесты. По территории форта спокойно     │ рекламируют и продают продукцию в            │                  │
│ гуляют кролики, которые дают посетителям себя │ «Инстаграме». Кстати, 68 процентов           │                  │
│ погладить.                                    │ пользователей в «Инстаграме» — женщины.      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Его пригласили на интервью в эту компанию и   │ Эта поездка помогла мне лучше узнать Россию  │ [0.8367, 0.1633] │
│ взяли на работу, потому что Сергей хорошо     │ и Украину, их историю и современность. Я     │                  │
│ знал английский язык.                         │ думаю, что я поеду в Крым ещё раз.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Фотография с цветущим деревом во дворе жилого │ Она сказала, что Ульяна — очень серьёзная    │ [0.7974, 0.2026] │
│ дома размещена в социальных сетях в группе «Я │ девушка и у неё уже есть молодой человек.    │                  │
│ живу в Красноярске».                          │ Его зовут Владимир.                          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Однако, чтобы не обидеть уже немолодого       │ Спартаковцы ехали на футбол, и их болельщики │ [0.6949, 0.3051] │
│ абитуриента, девушки сказали ему, что у него  │ ехали на футбол. В метро было много людей. К │                  │
│ очень красивое и выразительное лицо, и        │ счастью, футболисты никого не потеряли. Все  │                  │
│ посоветовали ему поступать на актёрский       │ приехали на стадион вовремя.                 │                  │
│ факультет.                                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Если у вашего собеседника есть домашний       │ И вы знаете, что случилось в этот вечер?!    │ [0.9713, 0.0287] │
│ любимец, он с удовольствием о нём расскажет   │ Анна тоже была на концерте. Это был также и  │                  │
│ и, может быть, покажет фотографии. хобби =    │ её любимый музыкант. Она не знала, что я     │                  │
│ увлечение. Всегда интересно говорить о хобби. │ хотел идти на концерт.                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ По мнению учёных, причиной экологической      │ Говорят, что московское метро очень красивое │ [0.8692, 0.1308] │
│ катастрофы, которая происходит на Земле, стал │ и удобное, — сказал Дэн. — Тогда я пойду     │                  │
│ человек. Каждый год растёт производство, а    │ пешком. Ходить пешком — полезно для          │                  │
│ это значит, что увеличивается количество      │ здоровья. Посмотрим, кто из нас придёт       │                  │
│ углекислого газа, увеличивается количество    │ первым!                                      │                  │
│ мусора, пыли.                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Именно по его совету Пётр принял решение об   │ – На самом деле никто не знает, что волнует  │ [0.5419, 0.4581] │
│ организации Великого посольства и сам         │ молодёжь. Молодые склонны копировать тот     │                  │
│ инкогнито, как простой рабочий, ездил в       │ стиль жизни, который пропагандируют          │                  │
│ составе этого посольства.                     │ масс-медиа.                                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Александр Гордон открыл конверт и объявил:    │ Она преподавала русский и литературу. Про    │ [0.9075, 0.0925] │
│ «Победил Дмитрий Сергеевич Чернавский, один   │ детство Я себя вообще помню очень рано, с    │                  │
│ из ведущих в мире специалистов по             │ того момента, когда меня собака укусила за   │                  │
│ теоретической биофизике». На сцену вышел      │ нос и за глаз, мне не было двух лет.         │                  │
│ очень энергичный, живой, весёлый человек.     │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Это и стало основой возникшего конфликта. Как │ Но партийным деятелям сначала удалось их     │ [0.7468, 0.2532] │
│ признался после эксперимента командир         │ уговорить на 40 дней повременить с преданием │                  │
│ экипажа, от злости на упрямого члена экипажа  │ тела земле («чтобы больше трудящихся         │                  │
│ в юбке он специально давал ей самую           │ попрощалось с вождём»), а потом эти сроки    │                  │
│ малоприятную работу.                          │ переросли в бессрочность.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В своём интервью журналу Financial Times в    │ В результате прогресса медицины и кризиса    │ [0.3499, 0.6501] │
│ 2010 году бизнесмен объявил, что хочет взять  │ пенсионной системы люди будут работать в     │                  │
│ пример с Билла Гейтса и Уоррена Баффета и     │ старости, а не жить на пенсию.               │                  │
│ отдать все свои деньги на благотворительные   │                                              │                  │
│ цели.                                         │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На территории этого монастыря можно увидеть   │ Но прокрастинация — это скорее симптом, чем  │ [0.6981, 0.3019] │
│ самое старое здание Москвы, сохранившееся до  │ болезнь. За хроническим «я сделаю это        │                  │
│ наших дней – Спасский собор.                  │ завтра» стоят страх неуспеха, боязнь оценки, │                  │
│                                               │ сложность выбора и другие самые главные      │                  │
│                                               │ проблемы человека XXI века.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Когда они пришли на следующий день в этот     │ После бани хорошо поплавать в холодном       │ [0.2747, 0.7253] │
│ парк, они не увидели Перельмана. Перельман не │ бассейне или принять холодный душ. И, как    │                  │
│ пришёл.                                       │ говорят в России, «С лёгким паром!».         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Баренц смог организовать выживание команды в  │ Естественно предположить, что пришельцы, как │ [0.6814, 0.3186] │
│ тяжёлых арктических условиях. Баренц и его    │ это всегда и бывает, осваивали в первую      │                  │
│ команда каждый день занимались спортом и      │ очередь побережье, истребляя попутно леса по │                  │
│ старались следить за здоровьем.               │ всему периметру континента.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Теперь при использовании гаджетов поход в     │ Вместо этого смотрите сообщения «ВКонтакте», │ [0.7978, 0.2022] │
│ музей часто оказывается более познавательным. │ проглядываете новости, пишете десяток других │                  │
│ Вы знакомитесь только с теми предметами,      │ писем, куда менее важных. В итоге сроки      │                  │
│ которые вам действительно интересны, и        │ сорваны, интимное свидание отменилось,       │                  │
│ получаете столько информации, сколько готовы  │ бизнес-партнёр обижен.                       │                  │
│ принять.                                      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Гости могут принести вам хлеб и соль, это     │ Конечно, люди делают очень много для семьи.  │ [0.9571, 0.0429] │
│ символический жест по немецкой традиции.      │ А когда люди делают то, что любят, мы        │                  │
│ Подарки дарят разные.                         │ говорим, что они делают это для души.        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Лебединое озеро» — наверно, самый известный  │ Но Наташа так не думает. Как хорошо, когда   │ [0.9791, 0.0209] │
│ русский балет, классическая версия которого   │ дома чисто и красиво! А вечером все дома.    │                  │
│ была поставлена в 1895 году, уже после смерти │ Все вместе ужинают, иногда смотрят           │                  │
│ Петра Ильича Чайковского.                     │ телевизор.                                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Мы отдалились от природы, поэтому не ценим и  │ Для чего люди работают? Самый простой ответ: │ [0.8966, 0.1034] │
│ не уважаем её. Природа отвечает нам тем же.   │ чтобы зарабатывать. Но это слишком просто!   │                  │
│ Примером может служить изменение погоды и     │ Если люди работают только для денег, почему  │                  │
│ климата на всей планете.                      │ не все выбирают работу, где самая высокая    │                  │
│                                               │ зарплата?                                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Проект «Поедем поедим!» был признан одной из  │ Он сделал важные открытия в области химии,   │ [0.3364, 0.6636] │
│ лучших программ о путешествиях и получил      │ физики. Имя М. В. Ломоносова знает каждый    │                  │
│ премию журнала National Geographic Traveler   │ русский человек. В Москве и в                │                  │
│ Awards в 2016 году.                           │ Санкт-Петербурге есть памятники Михаилу      │                  │
│                                               │ Васильевичу Ломоносову.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Пасху отмечают в первое воскресенье после     │ «Морозко» — цветной музыкальный фильм. Это   │ [0.9307, 0.0693] │
│ весеннего полнолуния, между 4 апреля и 8 мая. │ хорошая история со счастливым концом. В      │                  │
│ Каждый год дату Пасхи вычисляют специально.   │ Германии уже много лет традиционно смотрят   │                  │
│                                               │ фильм «Ужин на одного». Этот краткий         │                  │
│                                               │ набросок на английском языке.                │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В августе родители Наташи поехали отдыхать на │ Григорий Перельман — известный российский    │ [0.6122, 0.3878] │
│ юг, а Наташа осталась с бабушкой дома. Наташа │ математик. Он учился в университете в        │                  │
│ пообещала родителям читать каждый день 30     │ Санкт-Петербурге. Он хорошо сдавал экзамены  │                  │
│ страниц романа «Война и мир».                 │ и получал отличные оценки.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Американские нейробиологи выяснили, что люди  │ В мозгу человека содержится очень сложная    │ [0.4732, 0.5268] │
│ в комнате, где вокруг лежат коробки из-под    │ модель окружающего мира. Она позволяет ему   │                  │
│ техники, вещи и ненужные бумаги, менее        │ определить своё место в той или иной         │                  │
│ внимательны. Лучше убрать лишние предметы!    │ окружающей структуре, чтобы исполнять разные │                  │
│                                               │ социальные роли.                             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ С женой они занимаются огородом и ведут       │ «Это прекрасная акция, которая в             │ [0.3314, 0.6686] │
│ маленький бизнес: продают мёд, натуральные    │ развлекательной форме привлекла внимание     │                  │
│ продукты питания, специи. Клиентов у Степана  │ миллионов. Судя по сборам, превысила все     │                  │
│ не так много, но зато все постоянные, многие  │ ожидания. Молодцы», — считает инвестор       │                  │
│ покупают оптом.                               │ Евгений Гордеев.                             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Утром первого сентября на улицах можно        │ Посмотрите, как Большой каскад переходит в   │ [0.3837, 0.6163] │
│ увидеть много детей с букетами цветов.        │ море с помощью Морского канала. Этот канал   │                  │
│ Начался новый учебный год, и по традиции в    │ делит Нижний парк на «Западную» и            │                  │
│ этот день дети приходят в школу с цветами.    │ «Восточную» части.                           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В этих соревнованиях побеждал тот молодой     │ Может быть, но, когда в экономике кризис,    │ [0.7713, 0.2287] │
│ человек, конь которого был первым в беге.     │ продавать дома и квартиры трудно. Ещё одна   │                  │
│ Постепенно Сабантуй стал всеобщим праздником. │ популярная инвестиция — золото, но где его   │                  │
│                                               │ хранить? В Америке популярно инвестировать в │                  │
│                                               │ акции.                                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На берегу красавицы реки Сылвы, в старинном   │ Работа экологов направлена на усиленную      │ [0.3525, 0.6475] │
│ городе Кунгуре, в холодной каменной горе      │ борьбу с такими факторами, они принимают ряд │                  │
│ находится Кунгурская ледяная пещера, которая  │ профилактических мер, снижая таким образом   │                  │
│ является настоящим национальным достоянием.   │ неблагоприятное воздействие на окружающую    │                  │
│ На каникулах я отправилась туда на экскурсию. │ среду.                                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я воспитательница, работаю в детском саду. У  │ И как подпольщики, они имели псевдонимы, и   │ [0.3098, 0.6902] │
│ меня в группе 10 детей. Я думаю, что режим    │ чтобы осознать свою связь с революционным    │                  │
│ дня — это очень важно для детей, потому что   │ движением, и конечно, из практических        │                  │
│ это их дисциплинирует.                        │ соображений, поскольку подпольные            │                  │
│                                               │ революционеры — это те люди, которых         │                  │
│                                               │ преследует власть.                           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ У меня столько дел, что некогда думать ни о   │ Я оставил в номере вещи, обменял деньги и    │ [0.6107, 0.3893] │
│ каком глобальном потеплении. Мой ребёнок      │ пошёл гулять по городу. В этот день я        │                  │
│ заболел: мы с ним под дождь попали, а зонт я  │ осмотрел достопримечательности Хельсинки,    │                  │
│ оставила дома.                                │ побывал в красивом парке.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Новый Год — праздник скорее светский, чем     │ И дело не только в количестве участников,    │ [0.6424, 0.3576] │
│ религиозный, поэтому его встречают в кругу    │ уровне привлечённых медийных лиц и объёме    │                  │
│ друзей, среди людей, близких по интересам. Ни │ собранных средств, но и в градусе            │                  │
│ один праздник не ждут с таким нетерпением,    │ сопровождающей дискуссии.                    │                  │
│ как Новый год.                                │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В СССР Первое мая было политическим           │ Но никто и не пытается вывести породу        │ [0.74, 0.26]     │
│ праздником, во время которого проводились     │ жирномолочных дрозофил. Они нужны, чтобы     │                  │
│ демонстрации трудящихся и военные парады.     │ изучать законы наследственности. Законы эти  │                  │
│                                               │ одинаковы для мухи и для слона. На слонах    │                  │
│                                               │ получите тот же результат.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вообще, это очень странно, что новичок может  │ В свободное время девушка много занималась   │ [0.4976, 0.5024] │

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Это значит, мы приезжаем к университету, вы   │ У меня есть подруга, я её очень люблю, и всё │ [0.4637, 0.5363] │
│ выходите из машины и идёте учиться. Отвозить  │ мне в ней нравится. У неё длинные густые     │                  │
│ или отвезти кого-то куда-то – это значит      │ волнистые каштановые волосы, высокий умный   │                  │
│ привезти человека в какое-то место и оставить │ лоб и вздёрнутый кверху задорный носик.      │                  │
│ там. Понятно?                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Форт № 11 «Дёнхофф» был построен в XIX веке и │ Сегодня это не просто миллионы селфи         │ [0.6943, 0.3057] │
│ хорошо сохранился. Здесь проходят экскурсии и │ туристов и моделей. Компании часто           │                  │
│ даже квесты. По территории форта спокойно     │ рекламируют и продают продукцию в            │                  │
│ гуляют кролики, которые дают посетителям себя │ «Инстаграме». Кстати, 68 процентов           │                  │
│ погладить.                                    │ пользователей в «Инстаграме» — женщины.      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Его пригласили на интервью в эту компанию и   │ Эта поездка помогла мне лучше узнать Россию  │ [0.8367, 0.1633] │
│ взяли на работу, потому что Сергей хорошо     │ и Украину, их историю и современность. Я     │                  │
│ знал английский язык.                         │ думаю, что я поеду в Крым ещё раз.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Фотография с цветущим деревом во дворе жилого │ Она сказала, что Ульяна — очень серьёзная    │ [0.7974, 0.2026] │
│ дома размещена в социальных сетях в группе «Я │ девушка и у неё уже есть молодой человек.    │                  │
│ живу в Красноярске».                          │ Его зовут Владимир.                          │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [9]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.039037931710481644 Я люблю читать книги.
0.16050927340984344 Сегодня хорошая погода.
0.3049352169036865 Мне нравится гулять в парке.
0.4095620810985565 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.46564415097236633 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.3463592529296875 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [10]:
results = evaluate_reward_model(pairwise_reward_model, level="B")
print(results)

{'level': 'B', 'pairwise_accuracy': 0.751219512195122, 'n_pairs': 410, 'mean_margin': 0.21784210205078125, 'A_mean': 0.24628077447414398, 'B_mean': 0.5709921717643738, 'C_mean': 0.47555774450302124}

In [11]:
results["model"] = "rugpt"
results["epochs"] = 2
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_rugpt_2_B.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,B,0.75122,410,0.217842,0.246281,0.570992,0.475558,rugpt,2

## 2 epochs - C

In [9]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="C")
    parser.add_argument("--model_name", type=str, default="ai-forever/rugpt3small_based_on_gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=2)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()

    print("MODEL:", args.model_name)
    print("LEVEL:", args.level)
    print("EPOCHS:", args.num_train_epochs)

    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

MODEL: ai-forever/rugpt3small_based_on_gpt2
LEVEL: C
EPOCHS: 2

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ai-forever/rugpt3small_based_on_gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Loading CEFR data...

Map:   0%|          | 0/945 [00:00<?, ? examples/s]

Filter:   0%|          | 0/945 [00:00<?, ? examples/s]

Map:   0%|          | 0/118 [00:00<?, ? examples/s]

Filter:   0%|          | 0/118 [00:00<?, ? examples/s]

Map:   0%|          | 0/119 [00:00<?, ? examples/s]

Filter:   0%|          | 0/119 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ МеМеМе) — первым поколением, сформировавшимся │ Сигареты, алкоголь, наркотики, соль, сахар,  │ [0.3592, 0.6408] │
│ при Интернете. ЯЯЯ взаимодействуют с миром    │ чипсы, газировка, энергетики (список можно   │                  │
│ круглые сутки, но в основном через экран,     │ продолжить) — всё это факторы, разрушающие   │                  │
│ фиксируя каждый свой шаг.                     │ здоровье. Отказаться от них трудно, но       │                  │
│                                               │ можно. Многое зависит от нашей воли и        │                  │
│                                               │ мотивации.                                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Крупные банки и их филиалы предоставляют      │ Вот что рассказала о своём сыне мать         │ [0.94, 0.06]     │
│ отличные условия для работы молодых           │ чемпиона Клара Каспарова: — Гарик родился 13 │                  │
│ специалистов, предлагая высокую оплату их     │ апреля 1963 года. Рос он здоровым спокойным  │                  │
│ труда и возможность хорошо отдохнуть во время │ мальчиком.                                   │                  │
│ отпуска.                                      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Православными себя называют 63 % наших        │ У нас в деревне люди везде ездят на машинах: │ [0.9703, 0.0297] │
│ сограждан, мусульманами — 6 %, католиками и   │ в магазин, к врачу, на пляж, на работу. Это  │                  │
│ буддистами — по 1 %, последователей других    │ дорого, потому что машина дорогая и бензин   │                  │
│ традиционных конфессий и того меньше, а 16 %  │ дорогой.                                     │                  │
│ населения страны записались в атеисты.        │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Затем разбивать их на куски и продавать       │ В 17:45 я иду в супермаркет и покупаю        │ [0.9918, 0.0082] │
│ крестьянам. Так часть крестьян уйдёт из       │ продукты. Потом я иду домой и готовлю ужин.  │                  │
│ общин, станет активнее переселяться в Сибирь. │ До ужина я ещё убираю квартиру. В 20:00 я    │                  │
│ Некоторые крепкие хозяева станут строить      │ ужинаю.                                      │                  │
│ хутора.                                       │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Очевидно, если литературный язык определяется │ Слово «экология» знают сейчас все люди. Как  │ [0.7969, 0.2031] │
│ как общий язык письменности того или иного    │ правило, его используют для характеристики   │                  │
│ народа (В. В. Виноградов), то остальные его   │ условий проживания: «хорошая (плохая)        │                  │
│ разновидности носят более узкий (с точки      │ экология», «в нашем районе – ужасная         │                  │
│ зрения употребления) характер.                │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Знакомые размеры фотокарточек сделали         │ Люди поздравляли ветеранов и вспоминали тех, │ [0.714, 0.286]   │
│ приложение сверхвостребованным сначала внутри │ кто погиб, кто ценой собственной жизни       │                  │
│ сообщества продвинутых пользователей, а чуть  │ завоевал эту победу. Есть несколько историй  │                  │
│ позже Инстаграм завоевал признание каждого    │ о людях, защищавших свою Родину. Я только    │                  │
│ владельца смартфона.                          │ раз видала рукопашный.                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Ещё в 1984 году их эксперименты над плодовыми │ Его операции записывали на видео и учили по  │ [0.8918, 0.1082] │
│ мушками дали огромный толчок в этой области,  │ ним многие поколения хирургов. Родился Фёдор │                  │
│ благодаря чему сейчас известен целый набор    │ Углов в Сибири, в далёкой деревне.           │                  │
│ генов и белков, влияющих на наше суточное     │                                              │                  │
│ поведение.                                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Впрочем, само время публикации «Сахарного     │ Для чего люди работают? Самый простой ответ: │ [0.7729, 0.2271] │
│ ребёнка» превращает недостаток в достоинство  │ чтобы зарабатывать. Но это слишком просто!   │                  │
│ — быть может, и правда поздно пытаться        │ Если люди работают только для денег, почему  │                  │
│ понять, как и в чём мы оказались.             │ не все выбирают работу, где самая высокая    │                  │
│                                               │ зарплата?                                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Уже в девять лет Александр Бородин сочинил    │ К сожалению, первоначальный вид собора не    │ [0.4538, 0.5462] │
│ первое музыкальное произведение — польку      │ сохранился до нашего времени. Но и сейчас    │                  │
│ «Элен». Он посвятил композицию своей первой   │ собор является одним из самых красивых       │                  │
│ возлюбленной Елене, взрослой подруге матери.  │ соборов в Москве, украшением Красной         │                  │
│ Композитор родился в Петербурге.              │ площади.                                     │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Не только молодёжь, но и более взрослые люди  │ Этому городу уже 500 лет. В Плёсе есть       │ [0.9934, 0.0066] │
│ — среди респондентов до 45 лет доля таких     │ Дом-музей художника Исаака Ильича Левитана.  │                  │
│ союзов практически одинакова.                 │ Этот известный художник очень любил природу, │                  │
│                                               │ поэтому он жил и работал в этом тихом        │                  │
│                                               │ зелёном городе.                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Православные и католики должны научиться     │ Студенты — люди, как правило, небогатые,     │ [0.9349, 0.0651] │
│ нести согласное свидетельство истины в тех    │ потому что они не работают. Так думал        │                  │
│ областях, в которых это возможно и            │ журналист. У него были такие вопросы: «Как   │                  │
│ необходимо. Человеческая цивилизация вступила │ вы отдыхаете, куда вы обычно ходите в        │                  │
│ в период эпохальных перемен».                 │ воскресенье?»                                │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ А теперь к вопросу о толерантности — вот      │ В советское время все фильмы принадлежали    │ [0.5215, 0.4785] │
│ каков был мой опыт, опыт легкомысленно        │ государству, т. к. снимались на              │                  │
│ миролюбивого москвича.                        │ государственные деньги, вопрос о             │                  │
│                                               │ коммерческом использовании произведений      │                  │
│                                               │ искусства не стоял так остро, как сейчас.    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Работа экологов направлена на усиленную       │ Но слава не вскружила ему голову, так как он │ [0.9847, 0.0153] │
│ борьбу с такими факторами, они принимают ряд  │ был не только умным, талантливым,            │                  │
│ профилактических мер, снижая таким образом    │ интеллигентным, но и скромным, трудолюбивым  │                  │
│ неблагоприятное воздействие на окружающую     │ человеком. Он очень много работал, ездил по  │                  │
│ среду.                                        │ стране.                                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Высокие густые ели, заросли лесных ягод,      │ Здравствуйте! Меня зовут Ю?рий, можно просто │ [0.7321, 0.2679] │
│ сказочных грибов и ароматных трав по колено.  │ Юра. Моя фамилия Дудь. Я видеоблогер. У меня │                  │
│ Воздух пропитан живым, свежим, прохладным.    │ прекрасная работа: я много путешествую и     │                  │
│ Насколько многогранна природа. Я понимаю, что │ снимаю видео.                                │                  │
│ похожих мест не найдёшь нигде.                │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Впервые этот праздник отметили в 1911 году,   │ Когда родители уходили, мы начинали          │ [0.9109, 0.0891] │
│ но только 19 марта, в Австрии, Дании,         │ заниматься хозяйством. Я сам убирал со       │                  │
│ Германии и Швейцарии.                         │ стола, бабушка мыла посуду, а дедушка её     │                  │
│                                               │ вытирал полотенцем и ставил в шкаф. Затем я  │                  │
│                                               │ подметал пол на кухне.                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В мозгу человека содержится очень сложная     │ 1 августа 1841 года Дмитрий Менделеев        │ [0.8444, 0.1556] │
│ модель окружающего мира. Она позволяет ему    │ успешно поступил в Тобольскую гимназию, но   │                  │
│ определить своё место в той или иной          │ учился без всякого интереса и имел средние   │                  │
│ окружающей структуре, чтобы исполнять разные  │ результаты почти по всем предметам.          │                  │
│ социальные роли.                              │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Только в первый день обсуждения для участия в │ Они хотят быть похожими на своих кумиров     │ [0.5819, 0.4181] │
│ прениях записались почти половина депутатов.  │ Илона Маска, Марка Цукерберга, Билла Гейтса  │                  │
│ Специально по аграрному вопросу несколько раз │ и Стива Джобса, бросивших учёбу в            │                  │
│ выступал в Думе сам Столыпин.                 │ университете, но добившихся больших успехов  │                  │
│                                               │ и ставших известными во всём мире.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ — Они оказались во многом схожими с теми,     │ Самые дорогие очки в мире стоят больше       │ [0.9878, 0.0122] │
│ которые возникли после 22 июня 1941 г., когда │ миллиона долларов, но не из-за дороговизны   │                  │
│ на Советский Союз напала фашистская           │ материалов, а благодаря своему известному    │                  │
│ Германия».                                    │ владельцу. Эти очки носил Джон Леннон,       │                  │
│                                               │ который страдал астигматизмом.               │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Он увлекался музыкой, играл на скрипке,       │ Он родился в 1871 году в крестьянской семье, │ [0.5583, 0.4417] │
│ занимался скульптурой. Аркадий Дмитриевич был │ все члены которой обладали крепким здоровьем │                  │
│ большим картёжником, однажды он выиграл       │ и большой физической силой. В юности Иван    │                  │
│ имение Колноберже недалеко от Ковно.          │ работал грузчиком в порту города             │                  │
│                                               │ Севастополя.                                 │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Цитата из ролика: «Иностранные граждане и     │ Его высота — шестьдесят пять метров. Для     │ [0.861, 0.139]   │
│ туристы обменивают доллары на советские рубли │ многих жителей планеты Земля он является     │                  │
│ — самую устойчивую в мире валюту». Население  │ символом Москвы. Это один из самых древних   │                  │
│ долго привыкает к новым номиналам. Фразы      │ храмов в России и одно из самых красивых     │                  │
│ типа: «60 копеек. Это что?»                   │ мест Москвы.                                 │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Это когда откладывание касается               │ Ежегодно в окружающую среду выбрасываются 85 │ [0.5895, 0.4105] │
│ принципиальных решений: выбора профессии,     │ миллиардов тонн отходов. Из-за большого      │                  │
│ создания семьи и т. д. Случай не такой уж и   │ количества машин и заводов в атмосферу       │                  │
│ редкий.                                       │ ежедневно попадает множество вредных         │                  │
│                                               │ веществ, загрязняющих её.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Общая сумма пожертвований превысила 700 тысяч │ Ник — красивый, талантливый человек,         │ [0.9578, 0.0422] │
│ рублей, позволив облегчить жизнь жестоко      │ окончивший театральную школу в России, а     │                  │
│ страдающим людям. Информированность о БАС во  │ теперь живущий в Англии. У него много        │                  │
│ всём мире повысилась настолько, что и мечтать │ проблем. Он безработный. У него нет денег.   │                  │
│ было невозможно.                              │ От него ушла жена.                           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вместо этого смотрите сообщения «ВКонтакте»,  │ Ни китайских партнёров, ни китайских         │ [0.3706, 0.6294] │
│ проглядываете новости, пишете десяток других  │ ресторанов, ни китайского языка — ничего     │                  │
│ писем, куда менее важных. В итоге сроки       │ китайского! После перерыва он снова          │                  │
│ сорваны, интимное свидание отменилось,        │ приступил к занятиям, но относился к ним     │                  │
│ бизнес-партнёр обижен.                        │ менее серьёзно и более философски.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Значительно сузилась сфера использования      │ Семейный уклад башкир, татар и других        │ [0.72, 0.28]     │
│ просторечия и жаргона. Изменение тематики     │ исламских народов, населявших Урал, следовал │                  │
│ художественной литературы, её обращение к     │ законам ислама, по которым женщина была      │                  │
│ повседневной жизни, наоборот, расширили       │ значительно ограничена в правах и поэтому во │                  │
│ использование средств литературной устной     │ всём слушалась мужа.                         │                  │
│ речи.                                         │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ И за всё это время мы сумели переработать, в  │ Отказ от одноразовых предметов подразумевает │ [0.6001, 0.3999] │
│ том числе сжечь, меньше 9%. Есть разные типы  │ поиск альтернативы среди многоразовых вещей. │                  │
│ пластика, они отличаются по химическому       │ Холщовая сумка предотвращает покупку тысяч   │                  │
│ составу, не все из них принимаются на         │ пластиковых пакетов, чашки-термосы сокращают │                  │
│ переработку.                                  │ использование одноразовых стаканчиков для    │                  │
│                                               │ кофе.                                        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Балансир раскачивался взад-вперёд, его        │ Марио — молодой дипломат. Работает в Москве, │ [0.8607, 0.1393] │
│ колебания передавались на регулятор хода, и   │ в посольстве. Но он не любит говорить, что   │                  │
│ тот регулировал скорость вращения механизма.  │ работает в посольстве.                       │                  │
│ В настоящее время всё большее распространение │                                              │                  │
│ получают электрические и электронные часы.    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Она преподавала русский и литературу. Про     │ Теперь при использовании гаджетов поход в    │ [0.3573, 0.6427] │
│ детство Я себя вообще помню очень рано, с     │ музей часто оказывается более                │                  │
│ того момента, когда меня собака укусила за    │ познавательным. Вы знакомитесь только с теми │                  │
│ нос и за глаз, мне не было двух лет.          │ предметами, которые вам действительно        │                  │
│                                               │ интересны, и получаете столько информации,   │                  │
│                                               │ сколько готовы принять.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Мы граничим с девятью субъектами федерации, и │ Третья Вологда обращена духовно и            │ [0.4729, 0.5271] │
│ каждый из них экономически более-менее        │ материально к Западу и обеим столицам —      │                  │
│ благополучен, не говоря уже о Татарстане,     │ Петербургу и Москве — и тому, что стоит за   │                  │

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ МеМеМе) — первым поколением, сформировавшимся │ Сигареты, алкоголь, наркотики, соль, сахар,  │ [0.3592, 0.6408] │
│ при Интернете. ЯЯЯ взаимодействуют с миром    │ чипсы, газировка, энергетики (список можно   │                  │
│ круглые сутки, но в основном через экран,     │ продолжить) — всё это факторы, разрушающие   │                  │
│ фиксируя каждый свой шаг.                     │ здоровье. Отказаться от них трудно, но       │                  │
│                                               │ можно. Многое зависит от нашей воли и        │                  │
│                                               │ мотивации.                                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Крупные банки и их филиалы предоставляют      │ Вот что рассказала о своём сыне мать         │ [0.94, 0.06]     │
│ отличные условия для работы молодых           │ чемпиона Клара Каспарова: — Гарик родился 13 │                  │
│ специалистов, предлагая высокую оплату их     │ апреля 1963 года. Рос он здоровым спокойным  │                  │
│ труда и возможность хорошо отдохнуть во время │ мальчиком.                                   │                  │
│ отпуска.                                      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Православными себя называют 63 % наших        │ У нас в деревне люди везде ездят на машинах: │ [0.9703, 0.0297] │
│ сограждан, мусульманами — 6 %, католиками и   │ в магазин, к врачу, на пляж, на работу. Это  │                  │
│ буддистами — по 1 %, последователей других    │ дорого, потому что машина дорогая и бензин   │                  │
│ традиционных конфессий и того меньше, а 16 %  │ дорогой.                                     │                  │
│ населения страны записались в атеисты.        │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Затем разбивать их на куски и продавать       │ В 17:45 я иду в супермаркет и покупаю        │ [0.9918, 0.0082] │
│ крестьянам. Так часть крестьян уйдёт из       │ продукты. Потом я иду домой и готовлю ужин.  │                  │
│ общин, станет активнее переселяться в Сибирь. │ До ужина я ещё убираю квартиру. В 20:00 я    │                  │
│ Некоторые крепкие хозяева станут строить      │ ужинаю.                                      │                  │
│ хутора.                                       │                                              │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [10]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.033042773604393005 Я люблю читать книги.
0.053913358598947525 Сегодня хорошая погода.
0.03546735271811485 Мне нравится гулять в парке.
0.7766793370246887 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.8545243740081787 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.8346555829048157 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [11]:
results = evaluate_reward_model(pairwise_reward_model, level="C")
print(results)

{'target_level': 'C', 'pairwise_accuracy': 0.865546218487395, 'tie_rate': 0.0, 'loss_rate': 0.13445378151260504, 'n_pairs': 119, 'mean_margin': 0.3058505654335022, 'std_margin': 0.28124526143074036, 'median_margin': 0.2985902428627014, 'A_mean': 0.09946602582931519, 'B_mean': 0.2591073513031006, 'C_mean': 0.4985193908214569, 'A_std': 0.1040613204240799, 'B_std': 0.18758131563663483, 'C_std': 0.22719290852546692, 'monotonic_ABC': True, 'spearman_cefr': 0.6004140415558545, 'spearman_pvalue': 0.0}

In [12]:
results["model"] = "rugpt"
results["epochs"] = 2
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_rugpt_2_C.csv", index=False)
df_results

,target_level,pairwise_accuracy,tie_rate,loss_rate,n_pairs,mean_margin,std_margin,median_margin,A_mean,B_mean,C_mean,A_std,B_std,C_std,monotonic_ABC,spearman_cefr,spearman_pvalue,model,epochs
0,C,0.865546,0.0,0.134454,119,0.305851,0.281245,0.29859,0.099466,0.259107,0.498519,0.104061,0.187581,0.227193,True,0.600414,0.0,rugpt,2

## 5 epochs - A

In [ ]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="A")
    parser.add_argument("--model_name", type=str, default="ai-forever/rugpt3small_based_on_gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=5)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()
    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ai-forever/rugpt3small_based_on_gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Loading CEFR data...

Map:   0%|          | 0/1519 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1519 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Filter:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Filter:   0%|          | 0/189 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Думали ли читатели рассказов Рэя Бредбери,    │ Слово «экология» знают сейчас все люди. Как  │ [0.9926, 0.0074] │
│ что в нашей жизни будут «социальные сети» и   │ правило, его используют для характеристики   │                  │
│ мобильные телефоны, о которых он писал?       │ условий проживания: «хорошая (плохая)        │                  │
│                                               │ экология», «в нашем районе – ужасная         │                  │
│                                               │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В 17:45 я иду в супермаркет и покупаю         │ В 1970 году с благословения Американской     │ [0.9995, 0.0005] │
│ продукты. Потом я иду домой и готовлю ужин.   │ академии религии Гэскин едет в тур по        │                  │
│ До ужина я ещё убираю квартиру. В 20:00 я     │ Америке — беседовать о духовности с          │                  │
│ ужинаю.                                       │ молодёжью. За ним, на машинах и школьных     │                  │
│                                               │ автобусах, едут его последователи.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я помню, несколько лет назад я была в банке.  │ Потратить деньги на какую-нибудь не очень    │ [0.9933, 0.0067] │
│ Там работал очень красивый мужчина. Мы        │ нужную вещь значит забыть на пару часов о    │                  │
│ познакомились, и он пригласил меня в кино.    │ проблемах в отношениях и на работе.          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вы его, конечно, тоже знаете, но называете    │ Мы отдалились от природы, поэтому не ценим и │ [0.9957, 0.0043] │
│ «русский салат». Ингредиенты в «Оливье» очень │ не уважаем её. Природа отвечает нам тем же.  │                  │
│ простые. Это картофель, морковь, зелёный      │ Примером может служить изменение погоды и    │                  │
│ горошек, яйца, солёные огурцы и мясо. Иногда  │ климата на всей планете.                     │                  │
│ этот салат делают без мяса.                   │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Этому городу уже 500 лет. В Плёсе есть        │ Г В этом сезоне нас чаще всего «лечили»      │ [0.9788, 0.0212] │
│ Дом-музей художника Исаака Ильича Левитана.   │ простуженные граждане, на остановке          │                  │
│ Этот известный художник очень любил природу,  │ ожидающие автобус. Помните, девушка          │                  │
│ поэтому он жил и работал в этом тихом зелёном │ «вылечила» от простуды стареющего рокера: —  │                  │
│ городе.                                       │ Апчхи. О, эта простуда.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На вертолёте он перелетел через Красное море, │ Гости могут принести вам хлеб и соль, это    │ [0.9939, 0.0061] │
│ прилетел в Аравию, а оттуда на машине поехал  │ символический жест по немецкой традиции.     │                  │
│ в Иран.                                       │ Подарки дарят разные.                        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Оно ему очень нравится. Послушайте: в         │ Суть в том, что ритейлеры перепродают        │ [0.9996, 0.0004] │
│ институте Антон показал книгу и автограф      │ небольшим магазинам товары, полученные от    │                  │
│ поэта Джону, Кларе, Марии и Анне. Антон       │ производителей со скидкой. В итоге они       │                  │
│ рассказал им, что поэт будет выступать в      │ сохраняют скидку за объём продаж, но до      │                  │
│ институте на вечере.                          │ реального покупателя эти скидки не доходят.  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Сейчас 7 часов 30 минут. Люди идут на работу. │ В 1935 году на Воробьёвых горах прошёл       │ [0.9919, 0.0081] │
│ Вот Иван Иванович. Он преподаватель. Он идёт  │ первый чемпионат СССР по прыжкам на лыжах с  │                  │
│ в университет. А это его жена. Она работает в │ трамплина и второй чемпионат СССР по         │                  │
│ библиотеке.                                   │ горнолыжному спорту.                         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Например, я покупал новую кофту, если на      │ С того времени несёт она свои воды в Енисей. │ [0.7564, 0.2436] │
│ улице была холодная погода, а утром я надел   │ А камень, который бросил Байкал, и сейчас    │                  │
│ только футболку. Результат — много            │ стоит на том же месте.                       │                  │
│ некачественных вещей, которые я не ношу.      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ — На Волхонке, недалеко от станции метро      │ Бутерброд — одно из самых любимых и простых  │ [0.0755, 0.9245] │
│ «Кропоткинская», — ответил им молодой         │ блюд, мы едим его на завтрак или на обед,    │                  │
│ человек. — А как добраться до музея? —        │ когда нет времени приготовить что-то другое. │                  │
│ Удобнее всего доехать на метро, здесь рядом   │                                              │                  │
│ станция метро «Арбатская».                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Рауль — студент из Испании. Он учится в       │ Полученные деньги она отдала сыну, чтобы он  │ [0.5396, 0.4604] │
│ Московском университете на экономическом      │ мог поехать в столицу и продолжить там своё  │                  │
│ факультете. Он учится не очень хорошо и       │ образование. Так летом 1954 года В. М.       │                  │
│ поэтому плохо сдаёт экзамены.                 │ Шукшин оказался в Москве.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ А как вы считаете, можно самостоятельно       │ В 1926 году её приняли в Музыкальный театр,  │ [0.469, 0.531]   │
│ изучить язык? Да, конечно. Очень важно        │ в котором несколько лет она пела в хоре и    │                  │
│ заниматься языком каждый день.                │ изучала актёрское мастерство.                │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Утром я везу подарки детям в детские сады или │ Столицей тогда была Москва, Петербург ещё не │ [0.9938, 0.0062] │
│ школы. Я играю с детьми, пою с ними песни, а  │ был построен. В Москве встреча Нового года   │                  │
│ они читают мне стихи. Вечером я везу подарки  │ проходила на Красной площади, где были       │                  │
│ взрослым.                                     │ массовые гуляния.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Целый год мать ухаживает за девушкой. Она     │ Иметь «крутой» мобильный телефон — мечта     │ [0.9846, 0.0154] │
│ кормит её, как ребёнка, даёт ей лекарство,    │ каждого подростка, ведь стоимость аппарата,  │                  │
│ проводит с ней всё свободное время. И         │ по их убеждению, красноречиво говорит о      │                  │
│ благодаря матери девушка выздоравливает.      │ «крутизне» его владельца.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я думаю, можно в кафе. Но я не знаю, где ты   │ Эта методика популярна в тёплых странах, где │ [0.755, 0.245]   │
│ живёшь. На какой улице? Там есть хорошее      │ много собак, которые живут на улице:         │                  │
│ кафе? Маша — Саше: Саша, можно встретиться в  │ Бангладеш, Румыния, Греция, Таиланд,         │                  │
│ кафе в центре города.                         │ Индонезия, Индия.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ История рассказывает о девочке, которая       │ Впервые этот праздник отметили в 1911 году,  │ [0.0724, 0.9276] │
│ попадает в нереальный мир под землёй. © Это   │ но только 19 марта, в Австрии, Дании,        │                  │
│ роман о трагической любви замужней женщины по │ Германии и Швейцарии.                        │                  │
│ имени Анна и офицера.                         │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Игорь: «В воскресенье я обычно хожу в         │ Или, например, были у него или не были       │ [0.9497, 0.0503] │
│ библиотеку. Только в этот день я могу не      │ карточки, которые в разные периоды           │                  │
│ ходить в университет».                        │ существовали и играли важную роль при        │                  │
│                                               │ покупке продуктов в СССР.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Эта статья не о таких людях, а о тех, кто     │ Всё это прошло перед её глазами, в её глазах │ [0.8749, 0.1251] │
│ решил отказаться от комфорта и отправился в   │ покоилась мудрость веков, и, глядя в них, я  │                  │
│ путешествие, чтобы увидеть весь мир. Слово    │ чувствовал себя совсем маленьким и нагим.    │                  │
│ «путешествовать» значит «идти пешком».        │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ После бани хорошо поплавать в холодном        │ Для лучшего запоминания также используются   │ [0.9287, 0.0713] │
│ бассейне или принять холодный душ. И, как     │ цвета, звуковые комбинации, яркие образы.    │                  │
│ говорят в России, «С лёгким паром!».          │ Правильно применяя метод дворца памяти,      │                  │
│                                               │ можно запомнить информацию на долгие годы.   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Потом мы рассказывали, чем мы занимаемся в    │ После ядерной войны с применением массового  │ [0.9999, 0.0001] │
│ свободное время. Сирпа любит гостей и с       │ секретного оружия от Российской Федерации    │                  │
│ удовольствием готовит. Клаус много гуляет,    │ осталась лишь небольшая часть, которая       │                  │
│ часто ездит в лес. Том занимается спортом.    │ называет себя Московской империей.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Ещё у него есть младший брат. Его зовут       │ Естественно предположить, что пришельцы, как │ [1.0, 0.0]       │
│ Валерий. Ему 38 лет. Он тоже хоккеист. Сейчас │ это всегда и бывает, осваивали в первую      │                  │
│ он уже не играет в хоккей, но он ещё          │ очередь побережье, истребляя попутно леса по │                  │
│ занимается спортом.                           │ всему периметру континента.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Город быстро стал торговым портом и           │ Вот несколько советов, которые помогут вашей │ [0.1498, 0.8502] │
│ культурным центром, одним из самых красивых   │ памяти работать хорошо. Соедините предмет и  │                  │
│ мест мира. Он не был похож на Москву, его     │ действие, которое вы делаете автоматически!  │                  │
│ строили по точному плану.                     │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Конечно, в час пик в общественном транспорте  │ Часто участники должны вести себя            │ [0.9864, 0.0136] │
│ очень много народу, и это не всегда приятно.  │ по-клоунски, и они перестают комплексовать:  │                  │
│ Молодые люди очень громко разговаривают по    │ «Я выгляжу как полный дурак и не боюсь       │                  │
│ мобильному телефону или слушают музыку.       │ посмеяться над собой».                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Как я любил тебя», — писал Пушкин». Клара:   │ У меня не было близкого друга, когда я       │ [0.6938, 0.3062] │
│ «Я очень рада, что была в Доме-музее Пушкина  │ училась в школе и университете, потому что я │                  │
│ на Арбате. Там на портрете я видела поэта и   │ была очень скромная, можно сказать, тихоня.  │                  │
│ его жену».                                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Но хорошие способности помогли ему стать      │ Общая сумма пожертвований превысила 700      │ [0.9975, 0.0025] │
│ студентом академии. Ему было очень трудно     │ тысяч рублей, позволив облегчить жизнь       │                  │
│ учиться: он был намного старше, чем другие    │ жестоко страдающим людям. Информированность  │                  │
│ ученики. Учился Ломоносов сначала в Москве,   │ о БАС во всём мире повысилась настолько, что │                  │
│ потом в Петербурге.                           │ и мечтать было невозможно.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Это очень хорошая ситуация, но есть проблема: │ — Наверное, это наивный вопрос, но, как вы   │ [0.4965, 0.5035] │
│ как инвестировать эти деньги? Когда ваши      │ считаете, деньги делают людей счастливыми? — │                  │
│ деньги дома — это непрактично, потому что     │ На этот вопрос у меня есть точный ответ:     │                  │
│ есть инфляция. Что делать?                    │ нет, не делают.                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Павел Дуров родился в Ленинграде 10 октября   │ Великий Новгород кормился ростовским хлебом  │ [0.9932, 0.0068] │
│ 1984 года. Его папа, профессор классической   │ и «зело страдал», когда дороги были          │                  │
│ филологии, несколько лет работал в Италии, в  │ непроезжи. Тысячу лет Ополье не устаёт       │                  │
│ Турине, и там Павел начал учиться в школе.    │ кормить человека.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ И вы знаете, что случилось в этот вечер?!     │ Сергей Петров — владелец крупной             │ [0.9943, 0.0057] │
│ Анна тоже была на концерте. Это был также и   │ компьютерной компании «Информатика». Сергей  │                  │
│ её любимый музыкант. Она не знала, что я      │ родился в Советском Союзе, в те годы, когда  │                  │
│ хотел идти на концерт.                        │ в стране такой профессии, как бизнесмен,     │                  │
│                                               │ вообще не существовало.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Реальный Рэп может читать только тот, кто    │ Они хотят быть похожими на своих кумиров     │ [0.5455, 0.4545] │
│ сам его пишет» — так комментирует Децл свою   │ Илона Маска, Марка Цукерберга, Билла Гейтса  │                  │
│ работу.                                       │ и Стива Джобса, бросивших учёбу в            │                  │
│                                               │ университете, но добившихся больших успехов  │                  │
│                                               │ и ставших известными во всём мире.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Студенты — люди, как правило, небогатые,      │ Это мог быть доклад министра или приём       │ [0.9974, 0.0026] │
│ потому что они не работают. Так думал         │ крупного сановника. В 17 часов следовал      │                  │
│ журналист. У него были такие вопросы: «Как вы │ обязательный чай. Чаепитие обычно            │                  │
│ отдыхаете, куда вы обычно ходите в            │ продолжалось не более получаса.              │                  │
│ воскресенье?»                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вечером вся семья дома. Папа читает газеты,   │ И сегодня во многих исламских странах можно  │ [0.9984, 0.0016] │
│ мама готовит ужин, Игорь делает домашнее      │ увидеть бездомных, голодных, худых собак.    │                  │
│ задание, а Лена играет.                       │ Правда, так не везде, например, в Стамбуле   │                  │
│                                               │ бездомные псы толстые и весёлые.             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ У Алины мало свободного времени, но у неё     │ Однако с советской стороны была проведена    │ [0.9999, 0.0001] │
│ есть много увлечений: она любит животных      │ артподготовка, которая нанесла сильный удар  │                  │
│ (особенно своих собак), прекрасно рисует и    │ по врагу, лишила его преимуществ             │                  │
│ мечтает открыть ресторан японской кухни.      │ неожиданности и не позволила немцам          │                  │
│                                               │ реализовать свой план.                       │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Думали ли читатели рассказов Рэя Бредбери,    │ Слово «экология» знают сейчас все люди. Как  │ [0.9926, 0.0074] │
│ что в нашей жизни будут «социальные сети» и   │ правило, его используют для характеристики   │                  │
│ мобильные телефоны, о которых он писал?       │ условий проживания: «хорошая (плохая)        │                  │
│                                               │ экология», «в нашем районе – ужасная         │                  │
│                                               │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В 17:45 я иду в супермаркет и покупаю         │ В 1970 году с благословения Американской     │ [0.9995, 0.0005] │
│ продукты. Потом я иду домой и готовлю ужин.   │ академии религии Гэскин едет в тур по        │                  │
│ До ужина я ещё убираю квартиру. В 20:00 я     │ Америке — беседовать о духовности с          │                  │
│ ужинаю.                                       │ молодёжью. За ним, на машинах и школьных     │                  │
│                                               │ автобусах, едут его последователи.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я помню, несколько лет назад я была в банке.  │ Потратить деньги на какую-нибудь не очень    │ [0.9933, 0.0067] │
│ Там работал очень красивый мужчина. Мы        │ нужную вещь значит забыть на пару часов о    │                  │
│ познакомились, и он пригласил меня в кино.    │ проблемах в отношениях и на работе.          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вы его, конечно, тоже знаете, но называете    │ Мы отдалились от природы, поэтому не ценим и │ [0.9957, 0.0043] │
│ «русский салат». Ингредиенты в «Оливье» очень │ не уважаем её. Природа отвечает нам тем же.  │                  │
│ простые. Это картофель, морковь, зелёный      │ Примером может служить изменение погоды и    │                  │
│ горошек, яйца, солёные огурцы и мясо. Иногда  │ климата на всей планете.                     │                  │
│ этот салат делают без мяса.                   │                                              │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.9999548196792603 Я люблю читать книги.
0.9997864365577698 Сегодня хорошая погода.
0.998775064945221 Мне нравится гулять в парке.
0.002800342161208391 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.00037846105988137424 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.0006221923395060003 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [ ]:
results = evaluate_reward_model(pairwise_reward_model, level="A")
print(results)

{'level': 'A', 'pairwise_accuracy': 0.9206349206349206, 'n_pairs': 189, 'mean_margin': 0.5501500964164734, 'A_mean': 0.9646997451782227, 'B_mean': 0.46428996324539185, 'C_mean': 0.22893282771110535}

In [ ]:
results["model"] = "rugpt"
results["epochs"] = 5
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_rugpt_5_A.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,A,0.920635,189,0.55015,0.9647,0.46429,0.228933,rugpt,5

## 5 epochs - B

In [8]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="B")
    parser.add_argument("--model_name", type=str, default="ai-forever/rugpt3small_based_on_gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=5)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()
    print("MODEL:", args.model_name)
    print("LEVEL:", args.level)
    print("EPOCHS:", args.num_train_epochs)
    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

MODEL: ai-forever/rugpt3small_based_on_gpt2
LEVEL: B
EPOCHS: 5

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ai-forever/rugpt3small_based_on_gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Loading CEFR data...

Map:   0%|          | 0/3273 [00:00<?, ? examples/s]

Filter:   0%|          | 0/3273 [00:00<?, ? examples/s]

Map:   0%|          | 0/408 [00:00<?, ? examples/s]

Filter:   0%|          | 0/408 [00:00<?, ? examples/s]

Map:   0%|          | 0/410 [00:00<?, ? examples/s]

Filter:   0%|          | 0/410 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Это значит, мы приезжаем к университету, вы   │ У меня есть подруга, я её очень люблю, и всё │ [0.8465, 0.1535] │
│ выходите из машины и идёте учиться. Отвозить  │ мне в ней нравится. У неё длинные густые     │                  │
│ или отвезти кого-то куда-то – это значит      │ волнистые каштановые волосы, высокий умный   │                  │
│ привезти человека в какое-то место и оставить │ лоб и вздёрнутый кверху задорный носик.      │                  │
│ там. Понятно?                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Форт № 11 «Дёнхофф» был построен в XIX веке и │ Сегодня это не просто миллионы селфи         │ [0.7655, 0.2345] │
│ хорошо сохранился. Здесь проходят экскурсии и │ туристов и моделей. Компании часто           │                  │
│ даже квесты. По территории форта спокойно     │ рекламируют и продают продукцию в            │                  │
│ гуляют кролики, которые дают посетителям себя │ «Инстаграме». Кстати, 68 процентов           │                  │
│ погладить.                                    │ пользователей в «Инстаграме» — женщины.      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Его пригласили на интервью в эту компанию и   │ Эта поездка помогла мне лучше узнать Россию  │ [0.168, 0.832]   │
│ взяли на работу, потому что Сергей хорошо     │ и Украину, их историю и современность. Я     │                  │
│ знал английский язык.                         │ думаю, что я поеду в Крым ещё раз.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Фотография с цветущим деревом во дворе жилого │ Она сказала, что Ульяна — очень серьёзная    │ [0.8519, 0.1481] │
│ дома размещена в социальных сетях в группе «Я │ девушка и у неё уже есть молодой человек.    │                  │
│ живу в Красноярске».                          │ Его зовут Владимир.                          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Однако, чтобы не обидеть уже немолодого       │ Спартаковцы ехали на футбол, и их болельщики │ [0.9756, 0.0244] │
│ абитуриента, девушки сказали ему, что у него  │ ехали на футбол. В метро было много людей. К │                  │
│ очень красивое и выразительное лицо, и        │ счастью, футболисты никого не потеряли. Все  │                  │
│ посоветовали ему поступать на актёрский       │ приехали на стадион вовремя.                 │                  │
│ факультет.                                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Если у вашего собеседника есть домашний       │ И вы знаете, что случилось в этот вечер?!    │ [0.9984, 0.0016] │
│ любимец, он с удовольствием о нём расскажет   │ Анна тоже была на концерте. Это был также и  │                  │
│ и, может быть, покажет фотографии. хобби =    │ её любимый музыкант. Она не знала, что я     │                  │
│ увлечение. Всегда интересно говорить о хобби. │ хотел идти на концерт.                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ По мнению учёных, причиной экологической      │ Говорят, что московское метро очень красивое │ [0.7854, 0.2146] │
│ катастрофы, которая происходит на Земле, стал │ и удобное, — сказал Дэн. — Тогда я пойду     │                  │
│ человек. Каждый год растёт производство, а    │ пешком. Ходить пешком — полезно для          │                  │
│ это значит, что увеличивается количество      │ здоровья. Посмотрим, кто из нас придёт       │                  │
│ углекислого газа, увеличивается количество    │ первым!                                      │                  │
│ мусора, пыли.                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Именно по его совету Пётр принял решение об   │ – На самом деле никто не знает, что волнует  │ [0.5837, 0.4163] │
│ организации Великого посольства и сам         │ молодёжь. Молодые склонны копировать тот     │                  │
│ инкогнито, как простой рабочий, ездил в       │ стиль жизни, который пропагандируют          │                  │
│ составе этого посольства.                     │ масс-медиа.                                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Александр Гордон открыл конверт и объявил:    │ Она преподавала русский и литературу. Про    │ [0.9752, 0.0248] │
│ «Победил Дмитрий Сергеевич Чернавский, один   │ детство Я себя вообще помню очень рано, с    │                  │
│ из ведущих в мире специалистов по             │ того момента, когда меня собака укусила за   │                  │
│ теоретической биофизике». На сцену вышел      │ нос и за глаз, мне не было двух лет.         │                  │
│ очень энергичный, живой, весёлый человек.     │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Это и стало основой возникшего конфликта. Как │ Но партийным деятелям сначала удалось их     │ [0.8615, 0.1385] │
│ признался после эксперимента командир         │ уговорить на 40 дней повременить с преданием │                  │
│ экипажа, от злости на упрямого члена экипажа  │ тела земле («чтобы больше трудящихся         │                  │
│ в юбке он специально давал ей самую           │ попрощалось с вождём»), а потом эти сроки    │                  │
│ малоприятную работу.                          │ переросли в бессрочность.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В своём интервью журналу Financial Times в    │ В результате прогресса медицины и кризиса    │ [0.0798, 0.9202] │
│ 2010 году бизнесмен объявил, что хочет взять  │ пенсионной системы люди будут работать в     │                  │
│ пример с Билла Гейтса и Уоррена Баффета и     │ старости, а не жить на пенсию.               │                  │
│ отдать все свои деньги на благотворительные   │                                              │                  │
│ цели.                                         │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На территории этого монастыря можно увидеть   │ Но прокрастинация — это скорее симптом, чем  │ [0.9675, 0.0325] │
│ самое старое здание Москвы, сохранившееся до  │ болезнь. За хроническим «я сделаю это        │                  │
│ наших дней – Спасский собор.                  │ завтра» стоят страх неуспеха, боязнь оценки, │                  │
│                                               │ сложность выбора и другие самые главные      │                  │
│                                               │ проблемы человека XXI века.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Когда они пришли на следующий день в этот     │ После бани хорошо поплавать в холодном       │ [0.0092, 0.9908] │
│ парк, они не увидели Перельмана. Перельман не │ бассейне или принять холодный душ. И, как    │                  │
│ пришёл.                                       │ говорят в России, «С лёгким паром!».         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Баренц смог организовать выживание команды в  │ Естественно предположить, что пришельцы, как │ [0.4634, 0.5366] │
│ тяжёлых арктических условиях. Баренц и его    │ это всегда и бывает, осваивали в первую      │                  │
│ команда каждый день занимались спортом и      │ очередь побережье, истребляя попутно леса по │                  │
│ старались следить за здоровьем.               │ всему периметру континента.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Теперь при использовании гаджетов поход в     │ Вместо этого смотрите сообщения «ВКонтакте», │ [0.9247, 0.0753] │
│ музей часто оказывается более познавательным. │ проглядываете новости, пишете десяток других │                  │
│ Вы знакомитесь только с теми предметами,      │ писем, куда менее важных. В итоге сроки      │                  │
│ которые вам действительно интересны, и        │ сорваны, интимное свидание отменилось,       │                  │
│ получаете столько информации, сколько готовы  │ бизнес-партнёр обижен.                       │                  │
│ принять.                                      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Гости могут принести вам хлеб и соль, это     │ Конечно, люди делают очень много для семьи.  │ [0.9693, 0.0307] │
│ символический жест по немецкой традиции.      │ А когда люди делают то, что любят, мы        │                  │
│ Подарки дарят разные.                         │ говорим, что они делают это для души.        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Лебединое озеро» — наверно, самый известный  │ Но Наташа так не думает. Как хорошо, когда   │ [0.9293, 0.0707] │
│ русский балет, классическая версия которого   │ дома чисто и красиво! А вечером все дома.    │                  │
│ была поставлена в 1895 году, уже после смерти │ Все вместе ужинают, иногда смотрят           │                  │
│ Петра Ильича Чайковского.                     │ телевизор.                                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Мы отдалились от природы, поэтому не ценим и  │ Для чего люди работают? Самый простой ответ: │ [0.8804, 0.1196] │
│ не уважаем её. Природа отвечает нам тем же.   │ чтобы зарабатывать. Но это слишком просто!   │                  │
│ Примером может служить изменение погоды и     │ Если люди работают только для денег, почему  │                  │
│ климата на всей планете.                      │ не все выбирают работу, где самая высокая    │                  │
│                                               │ зарплата?                                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Проект «Поедем поедим!» был признан одной из  │ Он сделал важные открытия в области химии,   │ [0.1028, 0.8972] │
│ лучших программ о путешествиях и получил      │ физики. Имя М. В. Ломоносова знает каждый    │                  │
│ премию журнала National Geographic Traveler   │ русский человек. В Москве и в                │                  │
│ Awards в 2016 году.                           │ Санкт-Петербурге есть памятники Михаилу      │                  │
│                                               │ Васильевичу Ломоносову.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Пасху отмечают в первое воскресенье после     │ «Морозко» — цветной музыкальный фильм. Это   │ [0.9824, 0.0176] │
│ весеннего полнолуния, между 4 апреля и 8 мая. │ хорошая история со счастливым концом. В      │                  │
│ Каждый год дату Пасхи вычисляют специально.   │ Германии уже много лет традиционно смотрят   │                  │
│                                               │ фильм «Ужин на одного». Этот краткий         │                  │
│                                               │ набросок на английском языке.                │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В августе родители Наташи поехали отдыхать на │ Григорий Перельман — известный российский    │ [0.8055, 0.1945] │
│ юг, а Наташа осталась с бабушкой дома. Наташа │ математик. Он учился в университете в        │                  │
│ пообещала родителям читать каждый день 30     │ Санкт-Петербурге. Он хорошо сдавал экзамены  │                  │
│ страниц романа «Война и мир».                 │ и получал отличные оценки.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Американские нейробиологи выяснили, что люди  │ В мозгу человека содержится очень сложная    │ [0.6682, 0.3318] │
│ в комнате, где вокруг лежат коробки из-под    │ модель окружающего мира. Она позволяет ему   │                  │
│ техники, вещи и ненужные бумаги, менее        │ определить своё место в той или иной         │                  │
│ внимательны. Лучше убрать лишние предметы!    │ окружающей структуре, чтобы исполнять разные │                  │
│                                               │ социальные роли.                             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ С женой они занимаются огородом и ведут       │ «Это прекрасная акция, которая в             │ [0.1598, 0.8402] │
│ маленький бизнес: продают мёд, натуральные    │ развлекательной форме привлекла внимание     │                  │
│ продукты питания, специи. Клиентов у Степана  │ миллионов. Судя по сборам, превысила все     │                  │
│ не так много, но зато все постоянные, многие  │ ожидания. Молодцы», — считает инвестор       │                  │
│ покупают оптом.                               │ Евгений Гордеев.                             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Утром первого сентября на улицах можно        │ Посмотрите, как Большой каскад переходит в   │ [0.8621, 0.1379] │
│ увидеть много детей с букетами цветов.        │ море с помощью Морского канала. Этот канал   │                  │
│ Начался новый учебный год, и по традиции в    │ делит Нижний парк на «Западную» и            │                  │
│ этот день дети приходят в школу с цветами.    │ «Восточную» части.                           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В этих соревнованиях побеждал тот молодой     │ Может быть, но, когда в экономике кризис,    │ [0.9982, 0.0018] │
│ человек, конь которого был первым в беге.     │ продавать дома и квартиры трудно. Ещё одна   │                  │
│ Постепенно Сабантуй стал всеобщим праздником. │ популярная инвестиция — золото, но где его   │                  │
│                                               │ хранить? В Америке популярно инвестировать в │                  │
│                                               │ акции.                                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На берегу красавицы реки Сылвы, в старинном   │ Работа экологов направлена на усиленную      │ [0.835, 0.165]   │
│ городе Кунгуре, в холодной каменной горе      │ борьбу с такими факторами, они принимают ряд │                  │
│ находится Кунгурская ледяная пещера, которая  │ профилактических мер, снижая таким образом   │                  │
│ является настоящим национальным достоянием.   │ неблагоприятное воздействие на окружающую    │                  │
│ На каникулах я отправилась туда на экскурсию. │ среду.                                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я воспитательница, работаю в детском саду. У  │ И как подпольщики, они имели псевдонимы, и   │ [0.8073, 0.1927] │
│ меня в группе 10 детей. Я думаю, что режим    │ чтобы осознать свою связь с революционным    │                  │
│ дня — это очень важно для детей, потому что   │ движением, и конечно, из практических        │                  │
│ это их дисциплинирует.                        │ соображений, поскольку подпольные            │                  │
│                                               │ революционеры — это те люди, которых         │                  │
│                                               │ преследует власть.                           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ У меня столько дел, что некогда думать ни о   │ Я оставил в номере вещи, обменял деньги и    │ [0.667, 0.333]   │
│ каком глобальном потеплении. Мой ребёнок      │ пошёл гулять по городу. В этот день я        │                  │
│ заболел: мы с ним под дождь попали, а зонт я  │ осмотрел достопримечательности Хельсинки,    │                  │
│ оставила дома.                                │ побывал в красивом парке.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Новый Год — праздник скорее светский, чем     │ И дело не только в количестве участников,    │ [0.826, 0.174]   │
│ религиозный, поэтому его встречают в кругу    │ уровне привлечённых медийных лиц и объёме    │                  │
│ друзей, среди людей, близких по интересам. Ни │ собранных средств, но и в градусе            │                  │
│ один праздник не ждут с таким нетерпением,    │ сопровождающей дискуссии.                    │                  │
│ как Новый год.                                │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В СССР Первое мая было политическим           │ Но никто и не пытается вывести породу        │ [0.784, 0.216]   │
│ праздником, во время которого проводились     │ жирномолочных дрозофил. Они нужны, чтобы     │                  │
│ демонстрации трудящихся и военные парады.     │ изучать законы наследственности. Законы эти  │                  │
│                                               │ одинаковы для мухи и для слона. На слонах    │                  │
│                                               │ получите тот же результат.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вообще, это очень странно, что новичок может  │ В свободное время девушка много занималась   │ [0.4983, 0.5017] │

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Это значит, мы приезжаем к университету, вы   │ У меня есть подруга, я её очень люблю, и всё │ [0.8465, 0.1535] │
│ выходите из машины и идёте учиться. Отвозить  │ мне в ней нравится. У неё длинные густые     │                  │
│ или отвезти кого-то куда-то – это значит      │ волнистые каштановые волосы, высокий умный   │                  │
│ привезти человека в какое-то место и оставить │ лоб и вздёрнутый кверху задорный носик.      │                  │
│ там. Понятно?                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Форт № 11 «Дёнхофф» был построен в XIX веке и │ Сегодня это не просто миллионы селфи         │ [0.7655, 0.2345] │
│ хорошо сохранился. Здесь проходят экскурсии и │ туристов и моделей. Компании часто           │                  │
│ даже квесты. По территории форта спокойно     │ рекламируют и продают продукцию в            │                  │
│ гуляют кролики, которые дают посетителям себя │ «Инстаграме». Кстати, 68 процентов           │                  │
│ погладить.                                    │ пользователей в «Инстаграме» — женщины.      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Его пригласили на интервью в эту компанию и   │ Эта поездка помогла мне лучше узнать Россию  │ [0.168, 0.832]   │
│ взяли на работу, потому что Сергей хорошо     │ и Украину, их историю и современность. Я     │                  │
│ знал английский язык.                         │ думаю, что я поеду в Крым ещё раз.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Фотография с цветущим деревом во дворе жилого │ Она сказала, что Ульяна — очень серьёзная    │ [0.8519, 0.1481] │
│ дома размещена в социальных сетях в группе «Я │ девушка и у неё уже есть молодой человек.    │                  │
│ живу в Красноярске».                          │ Его зовут Владимир.                          │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [9]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.019353246316313744 Я люблю читать книги.
0.025055930018424988 Сегодня хорошая погода.
0.07095491886138916 Мне нравится гулять в парке.
0.23864677548408508 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.20983430743217468 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.13976982235908508 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [10]:
results = evaluate_reward_model(pairwise_reward_model, level="B")
print(results)

{'level': 'B', 'pairwise_accuracy': 0.775609756097561, 'n_pairs': 410, 'mean_margin': 0.33037057518959045, 'A_mean': 0.28014907240867615, 'B_mean': 0.8573374152183533, 'C_mean': 0.6046276092529297}

In [11]:
results["model"] = "rugpt"
results["epochs"] = 5
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_rugpt_5_B.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,B,0.77561,410,0.330371,0.280149,0.857337,0.604628,rugpt,5

## 8 epochs - A

In [ ]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="A")
    parser.add_argument("--model_name", type=str, default="ai-forever/rugpt3small_based_on_gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=8)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()

    print("MODEL:", args.model_name)
    print("LEVEL:", args.level)
    print("EPOCHS:", args.num_train_epochs)

    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

MODEL: ai-forever/rugpt3small_based_on_gpt2
LEVEL: A
EPOCHS: 8

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ai-forever/rugpt3small_based_on_gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Loading CEFR data...

Map:   0%|          | 0/1519 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1519 [00:00<?, ? examples/s]

Map:   0%|          | 0/191 [00:00<?, ? examples/s]

Filter:   0%|          | 0/191 [00:00<?, ? examples/s]

Map:   0%|          | 0/189 [00:00<?, ? examples/s]

Filter:   0%|          | 0/189 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Думали ли читатели рассказов Рэя Бредбери,    │ Слово «экология» знают сейчас все люди. Как  │ [0.9744, 0.0256] │
│ что в нашей жизни будут «социальные сети» и   │ правило, его используют для характеристики   │                  │
│ мобильные телефоны, о которых он писал?       │ условий проживания: «хорошая (плохая)        │                  │
│                                               │ экология», «в нашем районе – ужасная         │                  │
│                                               │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В 17:45 я иду в супермаркет и покупаю         │ В 1970 году с благословения Американской     │ [1.0, 0.0]       │
│ продукты. Потом я иду домой и готовлю ужин.   │ академии религии Гэскин едет в тур по        │                  │
│ До ужина я ещё убираю квартиру. В 20:00 я     │ Америке — беседовать о духовности с          │                  │
│ ужинаю.                                       │ молодёжью. За ним, на машинах и школьных     │                  │
│                                               │ автобусах, едут его последователи.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я помню, несколько лет назад я была в банке.  │ Потратить деньги на какую-нибудь не очень    │ [0.9999, 0.0001] │
│ Там работал очень красивый мужчина. Мы        │ нужную вещь значит забыть на пару часов о    │                  │
│ познакомились, и он пригласил меня в кино.    │ проблемах в отношениях и на работе.          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вы его, конечно, тоже знаете, но называете    │ Мы отдалились от природы, поэтому не ценим и │ [0.9999, 0.0001] │
│ «русский салат». Ингредиенты в «Оливье» очень │ не уважаем её. Природа отвечает нам тем же.  │                  │
│ простые. Это картофель, морковь, зелёный      │ Примером может служить изменение погоды и    │                  │
│ горошек, яйца, солёные огурцы и мясо. Иногда  │ климата на всей планете.                     │                  │
│ этот салат делают без мяса.                   │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Этому городу уже 500 лет. В Плёсе есть        │ Г В этом сезоне нас чаще всего «лечили»      │ [0.9817, 0.0183] │
│ Дом-музей художника Исаака Ильича Левитана.   │ простуженные граждане, на остановке          │                  │
│ Этот известный художник очень любил природу,  │ ожидающие автобус. Помните, девушка          │                  │
│ поэтому он жил и работал в этом тихом зелёном │ «вылечила» от простуды стареющего рокера: —  │                  │
│ городе.                                       │ Апчхи. О, эта простуда.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На вертолёте он перелетел через Красное море, │ Гости могут принести вам хлеб и соль, это    │ [1.0, 0.0]       │
│ прилетел в Аравию, а оттуда на машине поехал  │ символический жест по немецкой традиции.     │                  │
│ в Иран.                                       │ Подарки дарят разные.                        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Оно ему очень нравится. Послушайте: в         │ Суть в том, что ритейлеры перепродают        │ [1.0, 0.0]       │
│ институте Антон показал книгу и автограф      │ небольшим магазинам товары, полученные от    │                  │
│ поэта Джону, Кларе, Марии и Анне. Антон       │ производителей со скидкой. В итоге они       │                  │
│ рассказал им, что поэт будет выступать в      │ сохраняют скидку за объём продаж, но до      │                  │
│ институте на вечере.                          │ реального покупателя эти скидки не доходят.  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Сейчас 7 часов 30 минут. Люди идут на работу. │ В 1935 году на Воробьёвых горах прошёл       │ [0.9995, 0.0005] │
│ Вот Иван Иванович. Он преподаватель. Он идёт  │ первый чемпионат СССР по прыжкам на лыжах с  │                  │
│ в университет. А это его жена. Она работает в │ трамплина и второй чемпионат СССР по         │                  │
│ библиотеке.                                   │ горнолыжному спорту.                         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Например, я покупал новую кофту, если на      │ С того времени несёт она свои воды в Енисей. │ [0.9958, 0.0042] │
│ улице была холодная погода, а утром я надел   │ А камень, который бросил Байкал, и сейчас    │                  │
│ только футболку. Результат — много            │ стоит на том же месте.                       │                  │
│ некачественных вещей, которые я не ношу.      │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ — На Волхонке, недалеко от станции метро      │ Бутерброд — одно из самых любимых и простых  │ [0.5164, 0.4836] │
│ «Кропоткинская», — ответил им молодой         │ блюд, мы едим его на завтрак или на обед,    │                  │
│ человек. — А как добраться до музея? —        │ когда нет времени приготовить что-то другое. │                  │
│ Удобнее всего доехать на метро, здесь рядом   │                                              │                  │
│ станция метро «Арбатская».                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Рауль — студент из Испании. Он учится в       │ Полученные деньги она отдала сыну, чтобы он  │ [0.9998, 0.0002] │
│ Московском университете на экономическом      │ мог поехать в столицу и продолжить там своё  │                  │
│ факультете. Он учится не очень хорошо и       │ образование. Так летом 1954 года В. М.       │                  │
│ поэтому плохо сдаёт экзамены.                 │ Шукшин оказался в Москве.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ А как вы считаете, можно самостоятельно       │ В 1926 году её приняли в Музыкальный театр,  │ [0.9929, 0.0071] │
│ изучить язык? Да, конечно. Очень важно        │ в котором несколько лет она пела в хоре и    │                  │
│ заниматься языком каждый день.                │ изучала актёрское мастерство.                │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Утром я везу подарки детям в детские сады или │ Столицей тогда была Москва, Петербург ещё не │ [0.9996, 0.0004] │
│ школы. Я играю с детьми, пою с ними песни, а  │ был построен. В Москве встреча Нового года   │                  │
│ они читают мне стихи. Вечером я везу подарки  │ проходила на Красной площади, где были       │                  │
│ взрослым.                                     │ массовые гуляния.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Целый год мать ухаживает за девушкой. Она     │ Иметь «крутой» мобильный телефон — мечта     │ [0.757, 0.243]   │
│ кормит её, как ребёнка, даёт ей лекарство,    │ каждого подростка, ведь стоимость аппарата,  │                  │
│ проводит с ней всё свободное время. И         │ по их убеждению, красноречиво говорит о      │                  │
│ благодаря матери девушка выздоравливает.      │ «крутизне» его владельца.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я думаю, можно в кафе. Но я не знаю, где ты   │ Эта методика популярна в тёплых странах, где │ [0.7253, 0.2747] │
│ живёшь. На какой улице? Там есть хорошее      │ много собак, которые живут на улице:         │                  │
│ кафе? Маша — Саше: Саша, можно встретиться в  │ Бангладеш, Румыния, Греция, Таиланд,         │                  │
│ кафе в центре города.                         │ Индонезия, Индия.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ История рассказывает о девочке, которая       │ Впервые этот праздник отметили в 1911 году,  │ [0.6734, 0.3266] │
│ попадает в нереальный мир под землёй. © Это   │ но только 19 марта, в Австрии, Дании,        │                  │
│ роман о трагической любви замужней женщины по │ Германии и Швейцарии.                        │                  │
│ имени Анна и офицера.                         │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Игорь: «В воскресенье я обычно хожу в         │ Или, например, были у него или не были       │ [0.9993, 0.0007] │
│ библиотеку. Только в этот день я могу не      │ карточки, которые в разные периоды           │                  │
│ ходить в университет».                        │ существовали и играли важную роль при        │                  │
│                                               │ покупке продуктов в СССР.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Эта статья не о таких людях, а о тех, кто     │ Всё это прошло перед её глазами, в её глазах │ [0.7114, 0.2886] │
│ решил отказаться от комфорта и отправился в   │ покоилась мудрость веков, и, глядя в них, я  │                  │
│ путешествие, чтобы увидеть весь мир. Слово    │ чувствовал себя совсем маленьким и нагим.    │                  │
│ «путешествовать» значит «идти пешком».        │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ После бани хорошо поплавать в холодном        │ Для лучшего запоминания также используются   │ [0.9962, 0.0038] │
│ бассейне или принять холодный душ. И, как     │ цвета, звуковые комбинации, яркие образы.    │                  │
│ говорят в России, «С лёгким паром!».          │ Правильно применяя метод дворца памяти,      │                  │
│                                               │ можно запомнить информацию на долгие годы.   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Потом мы рассказывали, чем мы занимаемся в    │ После ядерной войны с применением массового  │ [1.0, 0.0]       │
│ свободное время. Сирпа любит гостей и с       │ секретного оружия от Российской Федерации    │                  │
│ удовольствием готовит. Клаус много гуляет,    │ осталась лишь небольшая часть, которая       │                  │
│ часто ездит в лес. Том занимается спортом.    │ называет себя Московской империей.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Ещё у него есть младший брат. Его зовут       │ Естественно предположить, что пришельцы, как │ [1.0, 0.0]       │
│ Валерий. Ему 38 лет. Он тоже хоккеист. Сейчас │ это всегда и бывает, осваивали в первую      │                  │
│ он уже не играет в хоккей, но он ещё          │ очередь побережье, истребляя попутно леса по │                  │
│ занимается спортом.                           │ всему периметру континента.                  │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Город быстро стал торговым портом и           │ Вот несколько советов, которые помогут вашей │ [0.6877, 0.3123] │
│ культурным центром, одним из самых красивых   │ памяти работать хорошо. Соедините предмет и  │                  │
│ мест мира. Он не был похож на Москву, его     │ действие, которое вы делаете автоматически!  │                  │
│ строили по точному плану.                     │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Конечно, в час пик в общественном транспорте  │ Часто участники должны вести себя            │ [0.9995, 0.0005] │
│ очень много народу, и это не всегда приятно.  │ по-клоунски, и они перестают комплексовать:  │                  │
│ Молодые люди очень громко разговаривают по    │ «Я выгляжу как полный дурак и не боюсь       │                  │
│ мобильному телефону или слушают музыку.       │ посмеяться над собой».                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Как я любил тебя», — писал Пушкин». Клара:   │ У меня не было близкого друга, когда я       │ [0.7948, 0.2052] │
│ «Я очень рада, что была в Доме-музее Пушкина  │ училась в школе и университете, потому что я │                  │
│ на Арбате. Там на портрете я видела поэта и   │ была очень скромная, можно сказать, тихоня.  │                  │
│ его жену».                                    │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Но хорошие способности помогли ему стать      │ Общая сумма пожертвований превысила 700      │ [0.9999, 0.0001] │
│ студентом академии. Ему было очень трудно     │ тысяч рублей, позволив облегчить жизнь       │                  │
│ учиться: он был намного старше, чем другие    │ жестоко страдающим людям. Информированность  │                  │
│ ученики. Учился Ломоносов сначала в Москве,   │ о БАС во всём мире повысилась настолько, что │                  │
│ потом в Петербурге.                           │ и мечтать было невозможно.                   │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Это очень хорошая ситуация, но есть проблема: │ — Наверное, это наивный вопрос, но, как вы   │ [0.9967, 0.0033] │
│ как инвестировать эти деньги? Когда ваши      │ считаете, деньги делают людей счастливыми? — │                  │
│ деньги дома — это непрактично, потому что     │ На этот вопрос у меня есть точный ответ:     │                  │
│ есть инфляция. Что делать?                    │ нет, не делают.                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Павел Дуров родился в Ленинграде 10 октября   │ Великий Новгород кормился ростовским хлебом  │ [0.9999, 0.0001] │
│ 1984 года. Его папа, профессор классической   │ и «зело страдал», когда дороги были          │                  │
│ филологии, несколько лет работал в Италии, в  │ непроезжи. Тысячу лет Ополье не устаёт       │                  │
│ Турине, и там Павел начал учиться в школе.    │ кормить человека.                            │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ И вы знаете, что случилось в этот вечер?!     │ Сергей Петров — владелец крупной             │ [1.0, 0.0]       │
│ Анна тоже была на концерте. Это был также и   │ компьютерной компании «Информатика». Сергей  │                  │
│ её любимый музыкант. Она не знала, что я      │ родился в Советском Союзе, в те годы, когда  │                  │
│ хотел идти на концерт.                        │ в стране такой профессии, как бизнесмен,     │                  │
│                                               │ вообще не существовало.                      │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ «Реальный Рэп может читать только тот, кто    │ Они хотят быть похожими на своих кумиров     │ [0.7226, 0.2774] │
│ сам его пишет» — так комментирует Децл свою   │ Илона Маска, Марка Цукерберга, Билла Гейтса  │                  │
│ работу.                                       │ и Стива Джобса, бросивших учёбу в            │                  │
│                                               │ университете, но добившихся больших успехов  │                  │
│                                               │ и ставших известными во всём мире.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Студенты — люди, как правило, небогатые,      │ Это мог быть доклад министра или приём       │ [1.0, 0.0]       │
│ потому что они не работают. Так думал         │ крупного сановника. В 17 часов следовал      │                  │
│ журналист. У него были такие вопросы: «Как вы │ обязательный чай. Чаепитие обычно            │                  │
│ отдыхаете, куда вы обычно ходите в            │ продолжалось не более получаса.              │                  │
│ воскресенье?»                                 │                                              │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вечером вся семья дома. Папа читает газеты,   │ И сегодня во многих исламских странах можно  │ [0.9999, 0.0001] │
│ мама готовит ужин, Игорь делает домашнее      │ увидеть бездомных, голодных, худых собак.    │                  │
│ задание, а Лена играет.                       │ Правда, так не везде, например, в Стамбуле   │                  │
│                                               │ бездомные псы толстые и весёлые.             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ У Алины мало свободного времени, но у неё     │ Однако с советской стороны была проведена    │ [0.9999, 0.0001] │
│ есть много увлечений: она любит животных      │ артподготовка, которая нанесла сильный удар  │                  │
│ (особенно своих собак), прекрасно рисует и    │ по врагу, лишила его преимуществ             │                  │
│ мечтает открыть ресторан японской кухни.      │ неожиданности и не позволила немцам          │                  │
│                                               │ реализовать свой план.                       │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Думали ли читатели рассказов Рэя Бредбери,    │ Слово «экология» знают сейчас все люди. Как  │ [0.9744, 0.0256] │
│ что в нашей жизни будут «социальные сети» и   │ правило, его используют для характеристики   │                  │
│ мобильные телефоны, о которых он писал?       │ условий проживания: «хорошая (плохая)        │                  │
│                                               │ экология», «в нашем районе – ужасная         │                  │
│                                               │ экология». Эти слова понятны всем.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ В 17:45 я иду в супермаркет и покупаю         │ В 1970 году с благословения Американской     │ [1.0, 0.0]       │
│ продукты. Потом я иду домой и готовлю ужин.   │ академии религии Гэскин едет в тур по        │                  │
│ До ужина я ещё убираю квартиру. В 20:00 я     │ Америке — беседовать о духовности с          │                  │
│ ужинаю.                                       │ молодёжью. За ним, на машинах и школьных     │                  │
│                                               │ автобусах, едут его последователи.           │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Я помню, несколько лет назад я была в банке.  │ Потратить деньги на какую-нибудь не очень    │ [0.9999, 0.0001] │
│ Там работал очень красивый мужчина. Мы        │ нужную вещь значит забыть на пару часов о    │                  │
│ познакомились, и он пригласил меня в кино.    │ проблемах в отношениях и на работе.          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Вы его, конечно, тоже знаете, но называете    │ Мы отдалились от природы, поэтому не ценим и │ [0.9999, 0.0001] │
│ «русский салат». Ингредиенты в «Оливье» очень │ не уважаем её. Природа отвечает нам тем же.  │                  │
│ простые. Это картофель, морковь, зелёный      │ Примером может служить изменение погоды и    │                  │
│ горошек, яйца, солёные огурцы и мясо. Иногда  │ климата на всей планете.                     │                  │
│ этот салат делают без мяса.                   │                                              │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.9999927282333374 Я люблю читать книги.
0.9999852180480957 Сегодня хорошая погода.
0.9994509816169739 Мне нравится гулять в парке.
0.012728926725685596 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.004405633080750704 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.005335689056664705 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [ ]:
results = evaluate_reward_model(pairwise_reward_model, level="A")
print(results)

{'level': 'A', 'pairwise_accuracy': 0.9259259259259259, 'n_pairs': 189, 'mean_margin': 0.572459876537323, 'A_mean': 0.9822330474853516, 'B_mean': 0.4304565489292145, 'C_mean': 0.17710892856121063}

In [ ]:
results["model"] = "rugpt"
results["epochs"] = 8
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_rugpt_8_A.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,A,0.925926,189,0.57246,0.982233,0.430457,0.177109,rugpt,8

## 8 epochs - B

In [ ]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="B")
    parser.add_argument("--model_name", type=str, default="openai-community/gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=8)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()
    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at openai-community/gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Loading CEFR data...

Map:   0%|          | 0/3273 [00:00<?, ? examples/s]

Filter:   0%|          | 0/3273 [00:00<?, ? examples/s]

Map:   0%|          | 0/408 [00:00<?, ? examples/s]

Filter:   0%|          | 0/408 [00:00<?, ? examples/s]

Map:   0%|          | 0/410 [00:00<?, ? examples/s]

Filter:   0%|          | 0/410 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Фотография с цветущим деревом во дворе жилого │ Она сказала, что Ульяна — очень серьёзная    │ [0.5677, 0.4323] │
│ дома размещена в социальных сетях в группе «Я │ девушка и у неё уже есть молодой человек.    │                  │
│ живу в Красноярске».                          │ Его зовут Владимир.                          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Когда они пришли на следующий день в этот     │ После бани хорошо поплавать в холодном       │ [0.5379, 0.4621] │
│ парк, они не увидели Перельмана. Перельман не │ бассейне или принять холодный душ. И, как    │                  │
│ пришёл.                                       │ говорят в России, «С лёгким паром!».         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Теперь всё изменилось: в социальных сетях     │ В римской бане тёплый пол, а горячий идёт из │ [0.427, 0.573]   │
│ люди заводят отношения с теми, кого никогда   │ стен, температура там градусов 70. Римские   │                  │
│ не видели.                                    │ бани были очень красивые.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ После Москвы он является вторым по величине   │ Погода была отличная: светило солнце, было   │ [0.5068, 0.4932] │
│ городом России, крупным промышленным, научным │ тепло, но не жарко. Я прекрасно провёл время │                  │
│ и историко-культурным центром.                │ с друзьями в Суздале!                        │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ С того времени несёт она свои воды в Енисей.  │ Именно за счёт него происходит рост,         │ [0.4408, 0.5592] │
│ А камень, который бросил Байкал, и сейчас     │ развитие и деление каждой клетки.            │                  │
│ стоит на том же месте.                        │ Контролируются эти процессы гормонами.       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Травмы можно получить даже после таких        │ А теперь к вопросу о толерантности — вот     │ [0.5433, 0.4567] │
│ простых и лёгких физических упражнений, как   │ каков был мой опыт, опыт легкомысленно       │                  │
│ бег или езда на велосипеде.                   │ миролюбивого москвича.                       │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ А баня — это для меня праздник! Я люблю и     │ В результате прогресса медицины и кризиса    │ [0.4403, 0.5597] │
│ финскую сауну, и турецкую баню. Но больше     │ пенсионной системы люди будут работать в     │                  │
│ всего мне нравится русская баня.              │ старости, а не жить на пенсию.               │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ На этих чтениях выступают с докладами и       │ Но сторонники ничего не говорят, они просто  │ [0.5927, 0.4073] │
│ научными сообщениями очень известные, а также │ играют в компьютерные игры, потому что им    │                  │
│ молодые учёные.                               │ это интересно.                               │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ 16 мая 1881 года галерея была открыта для     │ Катастрофа! У меня новые соседи! Они живут   │ [0.4876, 0.5124] │
│ посещения, и с этого времени количество       │ наверху, это большая и шумная семья. Папа —  │                  │
│ посетителей постоянно увеличивалось.          │ музыкант.                                    │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Фотография с цветущим деревом во дворе жилого │ Она сказала, что Ульяна — очень серьёзная    │ [0.5677, 0.4323] │
│ дома размещена в социальных сетях в группе «Я │ девушка и у неё уже есть молодой человек.    │                  │
│ живу в Красноярске».                          │ Его зовут Владимир.                          │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Когда они пришли на следующий день в этот     │ После бани хорошо поплавать в холодном       │ [0.5379, 0.4621] │
│ парк, они не увидели Перельмана. Перельман не │ бассейне или принять холодный душ. И, как    │                  │
│ пришёл.                                       │ говорят в России, «С лёгким паром!».         │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Теперь всё изменилось: в социальных сетях     │ В римской бане тёплый пол, а горячий идёт из │ [0.427, 0.573]   │
│ люди заводят отношения с теми, кого никогда   │ стен, температура там градусов 70. Римские   │                  │
│ не видели.                                    │ бани были очень красивые.                    │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ После Москвы он является вторым по величине   │ Погода была отличная: светило солнце, было   │ [0.5068, 0.4932] │
│ городом России, крупным промышленным, научным │ тепло, но не жарко. Я прекрасно провёл время │                  │
│ и историко-культурным центром.                │ с друзьями в Суздале!                        │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.27769985795021057 Я люблю читать книги.
0.2963213622570038 Сегодня хорошая погода.
0.2763323485851288 Мне нравится гулять в парке.
0.3064793050289154 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.3084152638912201 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.30679914355278015 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [ ]:
results = evaluate_reward_model(pairwise_reward_model, level="B")
print(results)

{'level': 'B', 'pairwise_accuracy': 0.5536585365853659, 'n_pairs': 410, 'mean_margin': 0.004355233162641525, 'A_mean': 0.29246601462364197, 'B_mean': 0.2985416352748871, 'C_mean': 0.2984464764595032}

In [ ]:
results["model"] = "gpt2"
results["epochs"] = 8
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_gpt2_8_B.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,B,0.553659,410,0.004355,0.292466,0.298542,0.298446,gpt2,8

## 8 epochs - C

In [ ]:
#from modeling.pairwise_reward_model import CEFRRewardModel
#from config import PairwiseRewardModelConfig
import torch
import argparse
import warnings

# changed for colab
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--level", type=str, default="C")
    parser.add_argument("--model_name", type=str, default="openai-community/gpt2")
    parser.add_argument("--num_labels", type=int, default=1)
    parser.add_argument("--train_batch_size", type=int, default=32)
    parser.add_argument("--eval_batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1.41e-5)
    parser.add_argument("--num_train_epochs", type=int, default=8)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=2)
    parser.add_argument("--output_dir", type=str, default="./reward_model/")
    parser.add_argument("--dataset_num_proc", type=int, default=64)
    parser.add_argument("--max_length", type=int, default=128)
    parser.add_argument("--wandb_project", type=str, default="CEFR-RewardModel")
    parser.add_argument("--wandb_exp_name", type=str, default=None)
    # changed for colab (was return parser.parse_args())
    return parser.parse_known_args()[0]


if __name__ == "__main__":

    if torch.cuda.device_count() > 1:
        warnings.warn(f"Multiple GPU Training has not been tested")
    args = parse_args()
    pairwise_reward_model_config = PairwiseRewardModelConfig(
        model_name=args.model_name,
        num_labels=args.num_labels,
        level=args.level,
        train_batch_size=args.train_batch_size,
        eval_batch_size=args.eval_batch_size,
        learning_rate=args.learning_rate,
        num_train_epochs=args.num_train_epochs,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        output_dir=args.output_dir,
        max_length=args.max_length,
        wandb_project=args.wandb_project,
        wandb_exp_name=args.wandb_exp_name
    )

    pairwise_reward_model = CEFRRewardModel(pairwise_reward_model_config)
    pairwise_reward_model.train()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at openai-community/gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Loading CEFR data...

Map:   0%|          | 0/945 [00:00<?, ? examples/s]

Filter:   0%|          | 0/945 [00:00<?, ? examples/s]

Map:   0%|          | 0/118 [00:00<?, ? examples/s]

Filter:   0%|          | 0/118 [00:00<?, ? examples/s]

Map:   0%|          | 0/119 [00:00<?, ? examples/s]

Filter:   0%|          | 0/119 [00:00<?, ? examples/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"
wandb: Using W&B in offline mode.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
Could not estimate the number of tokens of the input, floating-point operations will not be computed

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Логично было бы делать ряды этих товаров      │ А баня — это для меня праздник! Я люблю и    │ [0.4469, 0.5531] │
│ ближе ко входу, чтобы покупатели не тратили   │ финскую сауну, и турецкую баню. Но больше    │                  │
│ время, но происходит наоборот.                │ всего мне нравится русская баня.             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Именно за счёт него происходит рост, развитие │ Несмотря на то, что стены из белого камня    │ [0.692, 0.308]   │
│ и деление каждой клетки. Контролируются эти   │ были непрочными, название «Белокаменная»     │                  │
│ процессы гормонами.                           │ живёт и сегодня.                             │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ chosen_text                                   ┃ rejected_text                                ┃ logits           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Логично было бы делать ряды этих товаров      │ А баня — это для меня праздник! Я люблю и    │ [0.4469, 0.5531] │
│ ближе ко входу, чтобы покупатели не тратили   │ финскую сауну, и турецкую баню. Но больше    │                  │
│ время, но происходит наоборот.                │ всего мне нравится русская баня.             │                  │
├───────────────────────────────────────────────┼──────────────────────────────────────────────┼──────────────────┤
│ Именно за счёт него происходит рост, развитие │ Несмотря на то, что стены из белого камня    │ [0.692, 0.308]   │
│ и деление каждой клетки. Контролируются эти   │ были непрочными, название «Белокаменная»     │                  │
│ процессы гормонами.                           │ живёт и сегодня.                             │                  │
└───────────────────────────────────────────────┴──────────────────────────────────────────────┴──────────────────┘

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:2717: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(

In [ ]:
texts = [
    "Я люблю читать книги.",
    "Сегодня хорошая погода.",
    "Мне нравится гулять в парке.",
    "Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.",
    "С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.",
    "Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода."
]

scores = pairwise_reward_model.compute_rewards(texts)
for t, s in zip(texts, scores):
    print(float(s), t)

0.5724639296531677 Я люблю читать книги.
0.6114470958709717 Сегодня хорошая погода.
0.5905376076698303 Мне нравится гулять в парке.
0.7204639315605164 Несмотря на то, что рассматриваемая проблематика обладает многослойной структурой, её интерпретация требует дополнительной методологической рефлексии.
0.7067111134529114 С учётом вышеизложенного представляется необходимым пересмотреть методологические основания исследования.
0.743971586227417 Дискуссия о социокультурной обусловленности языковых практик требует междисциплинарного подхода.

In [ ]:
results = evaluate_reward_model(pairwise_reward_model, level="C")
print(results)

{'level': 'C', 'pairwise_accuracy': 0.5798319327731093, 'n_pairs': 119, 'mean_margin': -8.164533937815577e-05, 'A_mean': 0.6663765907287598, 'B_mean': 0.6791114211082458, 'C_mean': 0.6785526871681213}

In [ ]:
results["model"] = "gpt2"
results["epochs"] = 8
df_results = pd.DataFrame([results])
df_results.to_csv("reward_model_results_gpt2_8_C.csv", index=False)
df_results

,level,pairwise_accuracy,n_pairs,mean_margin,A_mean,B_mean,C_mean,model,epochs
0,C,0.579832,119,-0.000082,0.666377,0.679111,0.678553,gpt2,8